### ISSUE TITLE
As a task creator, I want to choose how many people I need to participate when creating my opportunity.

### ISSUE THREAD

**Issue by GailSwanson** [18F/midas#1003]
Include drop down of number of people needed to participate in the opportunity. Options should be the same as previously existed: 1 person, 2-5 people, More than 5 people, A Team
[18F_MIDAS_Taskv2.3.pdf](https://github.com/18F/midas/files/2344/18F_MIDAS_Taskv2.3.pdf)

**Comment by GailSwanson** [comment]
<img width="216" alt="screen shot 2015-09-22 at 11 59 40 am" src="https://cloud.githubusercontent.com/assets/12940398/10025355/73544930-6121-11e5-93a0-30c72d2f519c.png">

**Comment by ultrasaurus** [comment]
@dhcole this issue means that every task submitted requires an email exchange before it is posted.
