### ISSUE TITLE
No search results should still show something

### ISSUE THREAD

**Issue by polastre** [18F/midas#101]
When you search for a tag but there's no projects or opportunities associated with it, it should still show projects.  For example, the screen should say "Nothing matches your search, however these projects might be relevant..." and then a series of project cards.

@azmiria or @sharonlo feel free to proposal IA/UX.

**Comment by ultrasaurus** [comment]
proposal:  just add some hints here, in usability testing we found that sometimes people typed soemthijng like "how do I find an opportunity

-> @brandtheisey to propose some text

**Comment by brandtheisey** [comment]
![screen shot 2015-02-23 at 5 57 26 pm](https://cloud.githubusercontent.com/assets/7915386/6339634/cb1597ce-bb85-11e4-86e2-26267655e7b9.png)

Is this the kind of idea we are going for?

**Comment by ultrasaurus** [comment]
Yes, that's great!  We don't actually have a FAQ right now, but if you have one, just make the URL configurable and show that line if you have it.  Likewise, first line should only appear if Projects are enabled.

Thanks!
