### ISSUE TITLE
Get on Cloud Foundry

### ISSUE THREAD

**Issue by NoahKunin** [18F/midas#1028]
Looks like per AWS SDK and other things I see in the Console, this isn't on Cloud Foundry yet. It needs to be for any notable scope increase to be approved in the Open Data ATO vertical. Otherwise any future ATO is going to take forever.

**Comment by dhcole** [comment]
:+1: Per earlier conversations, we were keeping the infrastructure static through the ATO process. Moving to Could Foundry is first on my list once that's done. Just didn't want to complicate things during that process.

cc @ultrasaurus

**Comment by ultrasaurus** [comment]
@dhcole great to do the investigation, but note that this is needed "for any notable scope increase" which we don't anticipate in the next 6 months or so (which is our current funding level).  Of course, I know it will streamline other stuff, and would love to do it, once we understand that there'll be no net loss of services.

**Comment by dhcole** [comment]
This is pretty straight-forward. I moved over our dev / community test server: https://openopps-dev.18f.gov

The only blocker is https://github.com/18F/DevOps/issues/462 (our old EC2s provided access through an IAM role that is not available to CF instances)

Should be able 1 hour to migrate staging and production.

## Steps

- create new space
- create DB service in space
- `cf push` to create new app
- set environment variables for secrets
- `cf-ssh` to import data from old DB into new one
- switch domains in route53 to point to CF

**Comment by dhcole** [comment]
Followups will be:

- [ ] convert env vars to a user-provided service
- [ ] switch session store from pg to redis

**Comment by dhcole** [comment]
Blocked by https://github.com/18F/midas/issues/1046

**Comment by dhcole** [comment]
Blocked by 18F/DevOps#462

**Comment by dhcole** [comment]
Blockers have been resolved. PR is ready.
