### ISSUE TITLE
As an admin I noticed that several people do not have the tasks they participated in on their profiles page anymore.

### ISSUE THREAD

**Issue by LisaLNelson** [18F/midas#1032]
Several people do not have the tasks they participated in on their profiles anymore. They do show up on the landing page as having completed the tasks though.
Sara Cope
Bernetta Reese
Lisa Wald 

![image](https://cloud.githubusercontent.com/assets/9039852/10230551/b946d0da-684b-11e5-9f1c-4c579f307e04.png)

**Comment by dhcole** [comment]
@jeremiak mind taking a look at this? Perhaps something related to #962

**Comment by jeremiak** [comment]
@dhcole Yup, I'll take a look.

**Comment by dhcole** [comment]
@LisaLNelson This is fixed and will be in the next release.
