### ISSUE TITLE
As logged in user, I need The Achievements Wall to reflect who completed tasks with their photo.

### ISSUE THREAD

**Issue by LisaLNelson** [18F/midas#1034]
There seems to be a problem between the with the Achievements Wall and the the profiles.  I noticed that 2 of the people that worked on the task Building the White House led Citizen Science Toolkit were not on the Achievements wall and were not seen on the task Those people are Laura Kahn and Hutch Brown.  I sent them and email asked them to press the I'm in button again so they would show up with the other three that were there. (This is what it looked like)
![image](https://cloud.githubusercontent.com/assets/9039852/10249058/48f5be94-68f1-11e5-90ae-e32ba962bbb7.png)

So Laura Kahn clicked the I'm in button and on the achievements wall Bernetta's photo disappeared and their is no photo of Laura or circle where she would go.

![image](https://cloud.githubusercontent.com/assets/9039852/10249125/a1519504-68f1-11e5-9e7b-566421f77932.png)

**Comment by ultrasaurus** [comment]
from @jeremiak 

Right now we're only using the first three participants for displaying user avatars.

[Offending code here](https://github.com/18F/midas/blob/devel/assets/js/backbone/apps/home/templates/home_badges_feed_template.html#L24)

**Comment by jeremiak** [comment]
Does this get closed with #1036?

**Comment by dhcole** [comment]
Yea, I think this issue had two problems in it, one closed by #1045, and the other by #1036 once the participant who was deleted is added back.
