### ISSUE TITLE
Need database migration policy

### ISSUE THREAD

**Issue by polastre** [18F/midas#104]
We need to adopt tools and a policy for database migration from one version to the next.  The default sails behavior is `migrate:alter` but we really don't want that for production because it may cause the loss of data.  Instead, we want to add new columns (with a default value where appropriate), or allow for migration scripts to be committed as part of a sprint.  When sails is lifted in production, it should not be in `migrate:alter` mode, although this is okay for development.

Essentially we need:
- Migration policy documented, with location for migration scripts
- Different database initialization in production to keep the schema
- Development of any necessary migration/rollback tools

**Comment by ultrasaurus** [comment]
icebox this until we have a database change that requires it

**Comment by ultrasaurus** [comment]
this was addressed a while back, so it need not be in the icebox, can just remain closed
