### ISSUE TITLE
we can only see the first three participants on the logged in home page...

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#1040]
![image](https://cloud.githubusercontent.com/assets/41906/10292995/01e7d9f6-6b67-11e5-9411-647cba15ce01.png)

**Comment by jeremiak** [comment]
Right now we're only using the first three participants for displaying user avatars.

[Offending code here](https://github.com/18F/midas/blob/devel/assets/js/backbone/apps/home/templates/home_badges_feed_template.html#L24)

**Comment by ultrasaurus** [comment]
duplicate of https://github.com/18F/midas/issues/1034
