### ISSUE TITLE
we only see 4 participants, when there used to be 5

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#1041]
![image](https://cloud.githubusercontent.com/assets/41906/10293034/3aa4b25a-6b67-11e5-8c62-7968ad761ed8.png)

**Comment by jeremiak** [comment]
Checking the database for task [44](openopps.digitalgov.gov/tasks/44) shows that there are a total of 7 participant records: 4 active and 3 that have been deleted as participants (though those user records still exist).

I see that there are four active participants in the UI, in the API response, and in the database so I think we'll either need another opportunity to check out with the same bug or close this one out. @ultrasaurus, I think that is your call.

**Comment by dhcole** [comment]
Are we certain the task creator didn't just delete the participant?

**Comment by ultrasaurus** [comment]
@dhcole I think that is the most likely cause.  

I think we can't address this going backwards, but going forward, we probably want to log destructive events so we can tell what happened and correct for it manually.  We have some events in the activity stream... what would it take to add an event for when participants are removed?

**Comment by dhcole** [comment]
That wouldn't be too complicated but seems like a bit of chasing a new feature. There is no evidence of a bug. Probably just a miscommunication. We do have a deleted timestamp in the database.

**Comment by ultrasaurus** [comment]
I don't think we need to do this right now.  Would be good to know the timestamp to follow-up on this issue -- I can also check the email logs, which would confirm it too.  Then I will move to icebox and modify to be more solution-oriented for this inevitable human error that I expect to happen again.

**Comment by ultrasaurus** [comment]
I believe this is a user error, we need to be able to add the participant back:  https://github.com/18F/midas/issues/1036
and also need better ways to track this down in the future:  https://github.com/18F/midas/issues/1056
