### ISSUE TITLE
Change MyUSA redirect urls

### ISSUE THREAD

**Issue by dhcole** [18F/midas#1046]
Since we're no longer using the 18f.us domain, we need to update our MyUSA settings.

@ultrasaurus can you update the MyUSA settings for the dev and staging servers? The new domains are `https://openopps-test.18f.gov` and `https://openopps-staging.18f.gov`

**Comment by ultrasaurus** [comment]
@dhcole done!

**Comment by ultrasaurus** [comment]
FYI: tested both apps and they seem to work for me
