### ISSUE TITLE
As a user, I'd like to see an email address for questions

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#1073]
Eventually we'll want something more comprehensive for help, but for now, I was thinking of just adding something to the footer like:

Questions?  [send us email](openopps@gsa.gov)

**Comment by ultrasaurus** [comment]
@GailSwanson any thoughts about good words for this?

**Comment by GailSwanson** [comment]
Questions? Email us [email address]

**Comment by ultrasaurus** [comment]
@GailSwanson like this?

Questions? Email us: [openopps@gsa.gov](mailto:openopps@gsa.gov)
