### ISSUE TITLE
As a task creator I need to be able to add the number of people needed to the task when it is being created.

### ISSUE THREAD

**Issue by LisaLNelson** [18F/midas#1078]
Right now I can't add the number of people needed to the task creation form when it is initially drafted.

![image](https://cloud.githubusercontent.com/assets/9039852/10562243/8714ad0e-751f-11e5-98dd-804cb2378290.png)

After the initial opportunity has been created and saved you can go back in and an additional box appears and you can add the number of participants.

![image](https://cloud.githubusercontent.com/assets/9039852/10562254/45744052-7520-11e5-8ed1-55327054a174.png)

**Comment by ultrasaurus** [comment]
this should be fixed on staging:  https://github.com/18F/midas/issues/1003
