### ISSUE TITLE
I don't see tasks where I am a participant on my profile...

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#1098]
https://openopps-staging.18f.gov/profile/3

I tried changing task state from open to assigned, even to completed and I never saw anything on my profile....
![image](https://cloud.githubusercontent.com/assets/41906/10730047/a6c3a7b8-7baa-11e5-9dca-8f633534f5bf.png)

Here's the task where I'm participating:  https://openopps-staging.18f.gov/tasks/420

**Comment by dhcole** [comment]
I checked the 8 most recent participants on production and all had their completed opportunities listed. It looks like this may be an issue that's come up in work on staging that hasn't been released yet.

**Comment by ultrasaurus** [comment]
So, with this kind of regression, how do you want to handle prioritizing it?

**Comment by dhcole** [comment]
I think we should fix it before moving this release to production. I can look into it today.

**Comment by ultrasaurus** [comment]
me too.  Moved to top of backlog

**Comment by jeremiak** [comment]
So, looks like there are two bugs here: 1 for the API and one for the client.

The API response that populates this view (https://openopps-staging.18f.gov/api/user/activities/3) returns `null` as the first child of the `volTasks` array.

The client doesn't currently handle these types of error cases.

**Comment by jeremiak** [comment]
@dhcole any reason you can think of that [`newTask`](https://github.com/18F/midas/blob/dev/api/controllers/UserController.js#L221) would be a null object that gets pushed onto the array?
