### ISSUE TITLE
No way to change primary e-mail address

### ISSUE THREAD

**Issue by SandraYeaman** [18F/midas#140]
There doesn't appear to be a way to save any changes in the Account Information area of the user Profile. When I select a radio button to change the primary address, the Save Changes button isn't active. When I change something in one of the boxes above the Account Information area, the Save Changes button becomes active, but there is no change to which e-mail account is primary. Adding new accounts and deleting them works, but not changing the primary e-mail address

**Comment by dhcole** [comment]
What's the use case for having multiple email addresses for each user? We're not currently taking advantage of it. It would be great to simplify this by making email address an attribute of the user, rather than its own model.

cc @brandtheisey
