### ISSUE TITLE
As a developer, I would like to have simpler code with Sails associations

### ISSUE THREAD

**Issue by polastre** [18F/midas#145]
Much of what we do would benefit from associations -- less database accesses, more table joins, more performance, less nested javascript callbacks, less hackery.

This will completely change both the controllers that perform queries and the models.  Since the models will change so much, I'd really like to hold off on #104 until associations are implemented, because it isn't clear that we could migrate the database from the old non-associations strategy to the new associations v0.10 strategy.

**Comment by ultrasaurus** [comment]
We'll refactor at some point, icebox for now
