### ISSUE TITLE
Order of Tags in Opportunity summary is not consistent

### ISSUE THREAD

**Issue by SandraYeaman** [18F/midas#156]
For this project - https://ec2-96-127-44-122.us-gov-west-1.compute.amazonaws.com/projects/21 - the order of the tags entered through the mad libs for the Opportunities is not consistent on the Projects page. Since the order of the selection of the tags is fixed through the use of mad libs, this inconsistency of their order in the summary on the Projects page is at least curious, perhaps a clue to something else. Here is a list of the Opportunities and the order that the tags appear on the Projects page for each:

Identify privately owned islands of Indonesia
geography - real estate - 4-8 hours - GIS - Not Required - 1 person - Part Time - 1 Week

Identify owners and citienship of privately owned islands of Indonesia
geography - real estate - Wiki markup - Not Required - 1 person - Part Time - 25-40 hours - A Few Months

Identify privately owned islands of the Phillipines
geography - real estate - GIS - Not Required - 1 person - 9-24 hours - Part Time - 1 Week

Identify the privately owned islands of the Marshall Islands (same order as the second Indonesia opportunity)
geography - real estate - GIS - Not Required - 1 person - Part Time - 9-24 hours - 1 Week

Identify privately owned islands of FiJi and Idenfity private owned islands in the Solomon Islands chain - same order as the Marshall Islands Opportunity

Yet another problem
geography - Part Time - 1 person - Required - real estate - GIS - Less than 1 hour- 1 Day

**Comment by ultrasaurus** [comment]
this looks like it was addressed.  Closing.
