### ISSUE TITLE
Need a way to review closed opportunities

### ISSUE THREAD

**Issue by Chessen** [18F/midas#164]
When opportunities are closed, there is no way to find them by searching for them. The requestor can find them, and they still show up in the projects list and on the requestors profile, but a non-requestor user who searches for tags for a closed op wont find it. 

But you can find closed projects by searching for them. 

Why this matters: one of the goals of Midas is knowledge management and avoiding duplicate work. 

So we'll need a way for users to search closed ops.

Not sure if this is a bug or an enhancement. 

Related to #78

**Comment by ultrasaurus** [comment]
This has been addressed!  Now we have filters :)
