### ISSUE TITLE
Design tweak to the like module

### ISSUE THREAD

**Issue by Chessen** [18F/midas#177]
One of our oDesk designers came up with a nice design that removed the like module from the right column and centers it. Looks cleaner to me. Thoughts? 

![innovation2](https://cloud.githubusercontent.com/assets/4838006/3387385/b42de830-fc7d-11e3-94ec-8274a2565c9c.png)
![innovation](https://cloud.githubusercontent.com/assets/4838006/3387386/b42e21d8-fc7d-11e3-8c82-e85df5029d7e.png)

**Comment by ultrasaurus** [comment]
closing this, in favor of more holistic design approach:  https://github.com/18F/midas/issues/513
