### ISSUE TITLE
Distinguish between Opportunities that are available and those that have Volunteers

### ISSUE THREAD

**Issue by ReadG** [18F/midas#181]
Currently, if a user is seeking Opportunities to volunteer for, s/he has to go all the way onto the Opportunity page to see if it's available or not. 

Users need a way to quickly determine which Opportunities are available and seeking volunteers and which Opportunities are not. Note that this applies to the Opportunities & search landing pages as well as within the Opportunities 'box' of a Project page.

**Comment by ultrasaurus** [comment]
We now have an "Assigned" State
