### ISSUE TITLE
In project show view, allow users to associate existing opportunities with the project

### ISSUE THREAD

**Issue by polastre** [18F/midas#187]
When viewing a project, you may want to associate an opportunity with that project.  A button next to "Add Opportunity" could say "Associate Opportunity" (is there a better term) and let you select an opportunity that then gets assigned to this project.

If the opportunity already has a project that it is associated, provide a warning that the opportunity will lose its association with the old project.

Reported by @ekittrie and @ReadG

**Comment by ultrasaurus** [comment]
Since this is possible in opportunity screen, moving to icebox
