### ISSUE TITLE
When I Add a Project or Opportunity, I should see a description of what it is

### ISSUE THREAD

**Issue by polastre** [18F/midas#188]
The first time that the "Add Project" or "Add Opportunity" modal comes up, provide descriptive text that describes what a project or opportunity is.

Provide the user with a "Don't show this message again" dismiss button that stores in their preferences to hide this message in the future.  It could include a button/link at the top that says "More about Projects..." that you can click that shows the message again.

Reported by @ekittrie and @ReadG

**Comment by ultrasaurus** [comment]
closing this as its own issue, since we have an umbrella re-design issue that references this
