### ISSUE TITLE
I should not be able to create duplicate users or tags or add the same tag to a project multiple times

### ISSUE THREAD

**Issue by brandtheisey** [18F/midas#206]
Crowdwork has a number of duplicate item related bugs. 
1) Usernames can be created multiple times (under certain circumstances -- mostly by mashing the create button when the server is under load)
2) Tags can be created multiple times.
3) The same tag can be added to a project multiple times.

Sails/waterline doesn't appear to currently support multi-column indexes in general https://github.com/balderdashy/waterline/issues/523.

I can solve the user duplicate issue ( https://github.com/USStateDept/midas-crowdwork/issues/47) by changing the  user model to:
username: {
 type: 'STRING',
unique: true
}

and rebuilding my db.

However, the duplicate tag issue ( https://github.com/USStateDept/midas-crowdwork/issues/48 ) I think requires a composite unique key to solve. Obviously, I can add the constraints to the required tables, but since it isn't part of the app it is clearly not the long term solution and prone to getting over written and lost. In testing this, I also noticed that I can add the same tag to the same project repeatedly, so really I need a unique constraint in the tag table as well as well.

Is there something I've over looked or can do instead of changing the models / adding the constraints?

**Comment by afeld** [comment]
Would be good to force them all the skills/tags to downcase... I'm seeing "Open Source" and "open source", for example.

**Comment by polastre** [comment]
This used to be case insensitive because it used the `LIKE` operator, but I changed it when there was a bug in waterline.  I think this bug has now been fixed, so we should be able to use `.like()` again instead.  @dhcole would know better.  What do you think @dhcole?

Here's the commit in question:
https://github.com/18F/midas/commit/a3befc623d57f56416ec42a1090fd1db72ae2ad2

**Comment by polastre** [comment]
The bug in waterline is that it added `%` modifiers, so if you wrote "awesome open source" as a tag, it would match "open source", which is not the intended operation.  Now that waterline doesn't add `%` (correctly), we can use `.like()`.  Just wanted to give the full explanation.

**Comment by dhcole** [comment]
@polastre thanks for the background. I'll take try `.like()` and make sure it works as expected now.

**Comment by dhcole** [comment]
Users are now enforced as unique based on email address with #902 

Still need to clean up and tags and validate on creation to prevent new duplicate tags.

**Comment by dhcole** [comment]
Closing in favor of #999
