### ISSUE TITLE
when I upload a profile photo from my iPhone, it should appear with correct orientation

### ISSUE THREAD

**Issue by webermn** [18F/midas#239]
I uploaded a photo to my profile that was taken from my iPhone and the orientation was portrait. Upon upload to my profile, it was rotated 90 degrees counter-clockwise. This would be fine if I had tools to manually rotate it back to its proper orientation, but those don't appear to exist. 

Note: this was from testing on https://midas-test.18f.us.  (version 0.0.14)

**Comment by dhcole** [comment]
Haven't been able to recreate this. Please reopen again if you see it.
