### ISSUE TITLE
As a user, I should be able to see the filetype of an attachment

### ISSUE THREAD

**Issue by webermn** [18F/midas#241]
I attached a PNG and a PDF to an opportunity. Both displayed as type "file." 

1. Can MIME types be detected and the type be displayed for common files (PDF, images, documents/spreadsheets, etc.), rather than displaying as "file"?
2. For file types that can be viewed in the browser, can those be set to open in new tabs or as popup windows rather than having the default behavior be to download the file?

**Comment by ultrasaurus** [comment]
moving to icebox for now
