### ISSUE TITLE
Truncate the opportunity list entries to maintain list readability.

### ISSUE THREAD

**Issue by DavidEBest** [18F/midas#281]
The opportunity list entries can be arbitrarily long. To maintain the readability of the Project Task list, these should be truncated.
![screenshot 2014-09-29 13 19 05](https://cloud.githubusercontent.com/assets/933586/4445817/bedf4b32-47fc-11e4-9ced-ed29d39551e3.png)

**Comment by ultrasaurus** [comment]
icebox for now
