### ISSUE TITLE
Add /developer page 

### ISSUE THREAD

**Issue by gbinal** [18F/midas#299]
Along with #298, whenever there are any public APIs (or bulk access), **please** create a /developer page!   Here's a list of [known .gov developer hubs](http://18f.github.io/API-All-the-X/pages/developer_hubs).

**Comment by dhcole** [comment]
References:

- http://18f.github.io/API-All-the-X/pages/developer_hub_kit
- http://18f.github.io/API-All-the-X/pages/api_release_kit

**Comment by dhcole** [comment]
Here's draft content for this page. @ultrasaurus please take a look.

---

Midas is an open source application. We welcome developers to contribute to Midas and build applications that interface with its API.

# Contributing

To get started with Midas, [view the project on GitHub](https://github.com/18F/midas#readme)

# Developer API

Midas provides a JSON API for reading, creating, and updating tasks, user profiles, and projects. 

**This API is still experimental. Midas is under active development, and this API is subject to change.**

#### Authentication

Some API requests require authentication. To authenticate a request, add a valid MyUSA token as an `access_token` parameter to the request.

#### Contact

If you have questions or need help, please [post an issue on GitHub](https://github.com/18F/midas/issues).

## Tasks

### List all tasks

Returns JSON data for each task.

    GET /api/task/
 
### Get a single task

    GET /api/task/:taskId

### Create a task

    POST /api/task/

#### Parameters

Name | Type | Description
---|---|---
title | string | task title
description | string | task description
userId | integer | user id for the task owner
projectId | integer | project id of the parent project
state | string | state of task, either `draft`, `open`, `assigned`, or `closed`

### Update a task

    PUT /api/task/:taskId

#### Parameters

Name | Type | Description
---|---|---
title | string | task title
description | string | task description
userId | integer | user id for the task owner
projectId | integer | project id of the parent project
state | string | state of task, either `draft`, `open`, `assigned`, or `closed`


## Projects

### List all projects

Returns JSON data for each project.

    GET /api/project/findAll
 
### Get a single project

    GET /api/project/:projectId

### Create a project

    POST /api/project/

#### Parameters

Name | Type | Description
---|---|---
title | string | project title
description | string | project description

### Update a project

    PUT /api/project/:projectId

#### Parameters

Name | Type | Description
---|---|---
title | string | project title
description | string | project description


## Users

### Get a single user profile

    GET /api/user/:userId

### Update a project

    PUT /api/user/:userId

#### Parameters

Name | Type | Description
---|---|---
name | string | user's display name
title | string | user's professional title
bio | string | user's bio statement


## Locations

To assist forming location tags, Midas provides a geocoding interface based on GeoName's web service.

#### Suggest locations

Send a plain text location question, like `Washington, DC`, or `New York`

    GET /api/location/suggest?q=:locationQuery

**Comment by ultrasaurus** [comment]
just took a quick look and overall it looks great!  I would add a sample response to each section... unless we have tests that you can link to that have those.

**Comment by dhcole** [comment]
Sounds good. Should we host this off of the main application (`/developer`), which would mean it would be available on `midas-dev` as well as open opportunities, or host it on `18F.github.io/midas`?

**Comment by ultrasaurus** [comment]
I think that makes sense

**Comment by dhcole** [comment]
First pass is live here https://18f.github.io/midas/developer/

Needs some more work, but this at least gets our API out there.
