### ISSUE TITLE
Should I be able to post an opportunity when none personnel is needed?

### ISSUE THREAD

**Issue by coquiaspiazu** [18F/midas#306]
Task posted without personnel needed and then I was able to volunteer for that task. It seems that you'd have to need at least one person to post an opportunity.

![none personnel](https://cloud.githubusercontent.com/assets/8021492/4534236/6e45ac28-4da3-11e4-946f-11a4f35a23eb.png)

**Comment by ultrasaurus** [comment]
this got fixed!
