### ISSUE TITLE
after trying an e-mail address that already exists or is invalid, and then fixing it, all the error text and red colors should go away

### ISSUE THREAD

**Issue by louh** [18F/midas#309]
1. Click "Sign in" and then "Sign up now" on the bottom right
2. Attempt to create a new account, but use an e-mail that's already there, or an email that does not look valid. Click "Register."
3. After you get the "The email address is not valid or already in use" error message, go back and edit the e-mail address so that is a new e-mail address, or is valid.
4. You should see a green checkmark on the right, but the red highlight and error message are still present. This is confusing!

![screenshot 2014-10-06 18 07 27](https://cloud.githubusercontent.com/assets/2553268/4534414/2ea474a8-4da5-11e4-9778-88c845ffe058.png)

**Comment by dhcole** [comment]
Fixed by #539
