### ISSUE TITLE
Inside Opportunity Page, unclear who is a volunteer and who is the requestor

### ISSUE THREAD

**Issue by museful** [18F/midas#311]
The requestor is clear on the opportunity card, but not on the main opportunity page.  Suggest moving the requestor to the top box on the opportunity page.

![midas_opportunitypage](https://cloud.githubusercontent.com/assets/9043581/4535249/48079f1e-4db0-11e4-84fb-8b911f9b869c.jpg)

**Comment by ultrasaurus** [comment]
closing in favor of https://github.com/18F/midas/issues/513
