### ISSUE TITLE
I created a project, and added an opportunity to it...then they dissapeared.

### ISSUE THREAD

**Issue by museful** [18F/midas#312]
I created a project (Spinning Straw into Gold). Then I added an opportunity to that project (Gathering Straw). Once I completed the opportunity, I headed back to the home page. Neither project nor opportunity were displaying, and they also didn't show up within my profile.

Poof!

I was logged in to dev as claire.m.blaustein@irs.gov

**Comment by dhcole** [comment]
We've rewritten most of this part of the codebase, so I'm closing now. Please feel free to reopen if it comes up again.
