### ISSUE TITLE
A text box entry in the Add Opportunity modal could disappear if you hit Next before confirming the entry.

### ISSUE THREAD

**Issue by louh** [18F/midas#313]
From a user post-it at the 18F Hack Night: "Typing a line in a text box & hit 'next' - it disappears"

I think I have reproduced it here:

1. On a project page, click "Add Opportunity"
2. On the second page of the modal, enter a topic or skill in either of the two text boxes, but **do not** click in the dropdown to confirm your choice. ![screenshot 2014-10-06 19 44 00](https://cloud.githubusercontent.com/assets/2553268/4535374/ad3ab6a8-4db2-11e4-87b4-85558d79e6b0.png)
3. Click the "Next" button. This causes the dropdown to disappear, along with the user entry.

What's going on?

The user may not be understanding that they have to confirm the tag in the dropdown. Once they have typed the text, they immediately click the "Next" button. Instead of going to the next screen, however, this action simply cancels the dropdown action, causing the text to disappear. In addition, the dialog box doesn't forward to the next step, which may add to the confusion as to what is going on.

**Comment by dhcole** [comment]
Obsolete now that task creation happens on a single page.
