### ISSUE TITLE
After creating an opportunity, user expects to be taken to the opportunity

### ISSUE THREAD

**Issue by louh** [18F/midas#316]
From a post-it at the 18F Hack Night:

```
 Opportunities >
 Hit "Create" >
Didn't take me to
 My opportunity
```

(re-created in poem form)

I think the user is expecting the page to show the opportunity page that they just created, instead of remaining on the project page.

Related: #267, also reported at same hack night (from a different user). Users may be expecting some feedback of some kind, indicating success.

**Comment by ultrasaurus** [comment]
I believe this has been fixed
