### ISSUE TITLE
As a task creator, I need better prompts (Rework the new opportunity workflow)

### ISSUE THREAD

**Issue by gbinal** [18F/midas#318]
![img_20141006_204051](https://cloud.githubusercontent.com/assets/633088/4535804/ed28d8d2-4dba-11e4-8518-e4b819ac4617.jpg)

![img_20141006_204101](https://cloud.githubusercontent.com/assets/633088/4535805/f01ea062-4dba-11e4-8974-ca787deff7e4.jpg)

cc: @ultrasaurus

**Comment by chachasikes** [comment]
This is the product of a brainstorm where we looked at some existing Tapas project and acted out interviewing each other to see what sort of questions feel natural to elicit informative and impactful opportunity project descriptions.


What an opportunity creator has been doing before they create a new opportunity:
* A person wants to add an opportunity (a request for a fun professional development task)
* The person has already seen opportunities that exist
* Eventually a person might be able to watch a video about great tasks
* Log in
* If profile not filled out, ask to fill in profile.
* Begin adding new opportunity.

--------------------------------------------------------
Possible Steps (for progress feedback)
* estimated amount of time to fill out
* keep short and easy to fill out

Step 1:  What needs to happen?
Step 2:  Help people find your opportunity.

--------------------------------------------------------
Step 1: 
#### What needs to happen?

* Why is this important to you and your agency?
* Who will benefit from this? 
* Why is this opportunity important?
* What does success look like?
* Is this part of a bigger task?
* What will the opportunity look like if it is a success?
* What needs to be done?

Possible help prompts
- Describe your opportunity. 
- Include any links or photos if you have them.
- What needs to be done?
- What makes the opportunity interesting?
- See video on great opportunities
- Think of your opportunity in steps.

Design considerations:
- possibly smaller description box to keep the text short
- possible word limit count down


#### Who will benefit from this? 

Possible help prompts:
- both directly and indirectly
- who will interact with this when it is finished?
- What is the user need?

#### Why is this opportunity important?

Possible help prompts:
- What is the big vision? 

--------------------------------------------------------
Step 2: 
Help people find your opportunity.

#### Who are you?
You will be the primary contact for this opportunity.
Please [review your profile] to make sure that it mentions anything that might help a possible volunteer decide that you would be a great person to work with.

#### When do you need this?

Possible interfaces:
* calendar
* dropdown text (1 week, automatic date filled in, in the next month)

question: ongoing vs deadline?

#### Help potential volunteers find your opportunity.

(Some related questions that could also go under this category - maybe just as help prompts or in a video)
- Who would this opportunity be great for?
- Anything you need to know in advance?
- How many volunteers are you looking for?


### Create a great title for your opportunity
- Some good examples
- Writing good titles (link)


### Add some topic tags for your opportunity.

Possible help prompts:
* Brainstorm some categories for your opportunity. 
* Add tags for related government agencies.
* If you can't think of them all, don't worry. 
We have a community manager who will help make sure people find your opportunity.
[if there are sample tags related to the text]
* We found some suggested topics for you, select any that seem appropriate. 
* Examples: education, teaching, social media, video, storyboarding
camera work, post-production, microtasking, crowdsourcing


### About how long might this take someone?
* on-going
* a few hours
* ... other options

### Where do you need to be to work on this?
For example, if the opportunity is related to an event in a certain location.

That's all we need to know right now.


--------------------------------------------------------
Context

- how many steps to fill in & how long will it take?

things you need to know before beginning?

* Save as draft (always present)
* publish (when ready/moderated, required field done)
* wysiwyg elements (but close to the text editing interface)


Also Related & important
How to get back to editing mode:
-- my opportunities, on profile page: save as draft and edit (see in list as unpublished)

**Comment by ultrasaurus** [comment]
Here are some images to visualize the general workflow that @chachasikes and I brainstormed today.  These are very rough and we welcome additional iterations, feedback, wording suggestions....

![step 1 of 4](https://cloud.githubusercontent.com/assets/41906/5601012/b7892b54-929e-11e4-8945-6741528cf3b8.png)
![step 2 of 4](https://cloud.githubusercontent.com/assets/41906/5601015/b78b0a96-929e-11e4-86ea-7057e73979c8.png)
![step 3 of 4](https://cloud.githubusercontent.com/assets/41906/5601013/b78a4804-929e-11e4-871a-e528ec441632.png)
![step 4 of 4](https://cloud.githubusercontent.com/assets/41906/5601014/b78add96-929e-11e4-83de-32bffb004484.png)

**Comment by ultrasaurus** [comment]
related suggestion:  https://github.com/18F/midas/issues/188

**Comment by ultrasaurus** [comment]
feedback from @brandtheisey @MLBall : TOO MANY WORDS
"ML & I both like the general design but think there are too many words. Would about a version where the instructions are hidable via a more information icon (or something like it)?"

**Comment by GailSwanson** [comment]
Usability test was conducted on two versions of task creation interface: Version 1 modal multistep, version 2 single screen.
![openopps_prototype_onepg](https://cloud.githubusercontent.com/assets/12940398/8811171/bb2b5f3a-2fb9-11e5-90e6-f314b63ca36d.png)

**Comment by GailSwanson** [comment]
Refined based on user research.
![18f_midas_taskv2 1](https://cloud.githubusercontent.com/assets/12940398/8811192/ed5524dc-2fb9-11e5-9086-6cb6c26b3ec7.png)
![18f_midas_taskv2 1b](https://cloud.githubusercontent.com/assets/12940398/8811194/f3ab0e14-2fb9-11e5-929d-2a430fb69e51.png)

Action items from team feedback:
-Collapse Topics and Skills tags into one tag input field. Provide instruction text prompting users to tag both aspects of a task. Include in the task description section.
-Who, What, Where inputs still need refinement to fit scenarios
-Update "open opportunities staff" to be community focused and organization agnostic to support other deployments.

**Comment by GailSwanson** [comment]
New draft of task creation page. The one area we are still working on is the dynamic fields for step 3. That requires a bit more work. 
![18f_midas_taskv2 2](https://cloud.githubusercontent.com/assets/12940398/8935836/69d1c09c-3514-11e5-9f2b-fd159c32b9ea.png)

**Comment by jeremiak** [comment]
Hey @gailswanson in the current application we have some TOS-like text that the opportunity creator has to agree to. Here it is:

> We’re glad you want to create an opportunity! Before continuing please review the following responsibilities.
> 
> As a Creator I will:
>
> 1. Respond promptly and positively to opportunity takers
> 2. Lay out clear and realistic deliverables
> 3. Be clear about how much time is needed to complete the opportunity
> 4. Define the skills needed
> 5. Be prepared to onboard the opportunity taker. If the opportunity assigned is a simple one, take the time to explain it. If the opportunity is big or long-term, be prepared to mentor the participant.

Are we removing that entirely?

**Comment by jeremiak** [comment]
From @GailSwanson in chat:
> I need to touch base with Lisa on that, but if she wants to keep it, I want to put it at the end of the flow, not as a barrier in the beginning. My thought is that those get included in the confirmation message page and in the email that follows their task creation. More of a “here’s what you do next” sort of thing rather than an interstitial.

**Comment by jeremiak** [comment]
We're going to add the agreement to the end of the form.
