### ISSUE TITLE
Install instructions for Windows platform are incomplete / deficient

### ISSUE THREAD

**Issue by brandtheisey** [18F/midas#319]
A user at the GSA hackathon was unable to get the platform up and running after nearly 2.5 hours of effort, the last 90 minutes of which, I was driving his computer.

He had a Windows 7 Home Premium computer.

1) One of the problems relates to installing bcrypt on the window platform which despite being a node module, has a number of other requirements. This is his error screen after we installed dot 3.5 the vc++2012 and 2008 distributables and the 2008 Server SDK.

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Owner>cd midas

C:\Users\Owner\midas>npm install bcrypt
-
> bcrypt@0.7.7 install C:\Users\Owner\midas\node_modules\bcrypt
> node-gyp rebuild

C:\Users\Owner\midas\node_modules\bcrypt>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebu
ild
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3411: Could not load the Visual C++ component "VCBuild.exe". If the component is not installed, either 1) install the Microsoft Windows
 SDK for Windows Server 2008 and .NET Framework 3.5, or 2) install Microsoft Visual Studio 2008.  [C:\Users\Owner\midas\node_modules\bcrypt\build\binding.
sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Owner\midas\node_modules\bcrypt
gyp ERR! node -v v0.10.32
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! bcrypt@0.7.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.7.7 install script.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "bcrypt"
npm ERR! cwd C:\Users\Owner\midas
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

C:\Users\Owner\midas>npm install bcrypt
-
> bcrypt@0.7.7 install C:\Users\Owner\midas\node_modules\bcrypt
> node-gyp rebuild

C:\Users\Owner\midas\node_modules\bcrypt>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebu
ild
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
VCBUILD : error Message:  [C:\Users\Owner\midas\node_modules\bcrypt\build\binding.sln]
VCBUILD : System error : -2147154687. [C:\Users\Owner\midas\node_modules\bcrypt\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Owner\midas\node_modules\bcrypt
gyp ERR! node -v v0.10.32
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! bcrypt@0.7.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@0.7.7 install script.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "bcrypt"
npm ERR! cwd C:\Users\Owner\midas
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

2) the SQL commands in the windows section need to be clarified.

**Comment by anweiss** [comment]
You can use bcrypt on Windows but you'll want to ensure you have the following components installed:

1. Visual Studio 2013 (Express is sufficient)
2. Python 2.7.x
3. OpenSSL (http://slproweb.com/products/Win32OpenSSL.html)

Launch an instance of the Developer Command Prompt for VS2013 (which sets the appropriate MSBuild environment variables for you), navigate to the midas root directory, and execute `npm install`. This should install bcrypt appropriately.

We'll want to update the README to include these dependencies and instructions.

**Comment by dhcole** [comment]
@brandtheisey what's the latest here? Are the instructions up to date? Would be open to switching to https://github.com/dcodeIO/bcrypt.js. We've used it successfully on another project. It's essentially a drop-in replacement.
