### ISSUE TITLE
midas open source product needs a logo

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#335]
People find innovation.gov confusing and expect something to be at that domain (as far as I know there are no plans for that)
![image](https://cloud.githubusercontent.com/assets/41906/4593363/65e1cc26-5085-11e4-90d6-50c44470f9d0.png)

I suggest with come up with a simple placehoder midas logo. It will be overridden in each deployment, but will let us quickly identify dev & test servers, without confusing new open source contributors.

**Comment by ericadeahl** [comment]
Here's the logo on a white background
![midaslogo_transparent](https://cloud.githubusercontent.com/assets/5911280/5617421/93272514-94c3-11e4-9843-2000f6c2ecc3.png)

**Comment by polastre** [comment]
:+1: 

at some point we should trace this in illustrator so we have high res versions.

**Comment by ultrasaurus** [comment]
maybe @ericadeahl will add that to her queue -- then my request would be to make the # of stars match cabinet seats, which I think is 17 (15 + VP and President):

The Cabinet includes the Vice President and the heads of 15 executive departments — the Secretaries of Agriculture, Commerce, Defense, Education, Energy, Health and Human Services, Homeland Security, Housing and Urban Development, Interior, Labor, State, Transportation, Treasury, and Veterans Affairs, as well as the Attorney General. -- [whitehouse.gov](http://www.whitehouse.gov/administration/cabinet)

**Comment by ericadeahl** [comment]
Here's the logo without the small text, at 72px height and 60px height. Let's see if there's an existing vector asset we can use - otherwise I'll redraw when I get a chance. 
![midas_transparent_3](https://cloud.githubusercontent.com/assets/5911280/5618112/5a1d0156-94ca-11e4-9baa-27bf13333864.png)
![midas_transparent_3_60px](https://cloud.githubusercontent.com/assets/5911280/5618114/5c65b7aa-94ca-11e4-88b9-1469a02d32a2.png)

**Comment by ultrasaurus** [comment]
I sent email to @martymadrid to see if he has any original vector... tho it was quite a while ago now!

**Comment by ultrasaurus** [comment]
Here's what it looks like in-place:

![image](https://cloud.githubusercontent.com/assets/41906/5618780/16191204-94d1-11e4-845a-5ffcda501671.png)

I made the area for the logo 60px high -- will submit a PR shortly.

**Comment by polastre** [comment]
Hrm, the color palette of the logo doesn't really match the color palette of the site :confused:

**Comment by polastre** [comment]
We were in a rush when we started the project and didn't appropriately create (or use) the less/sass versions.  In retrospect, we shouldn't have cut that corner.  I agree that having a colors.less or something that compiles into the bootstrap L&F would be good.

**Comment by alwaysbrightblue** [comment]
Hm...  well for now @ericadeahl and @ultrasaurus, you can change the blue to #297BB5 to match the current styles in the project.

**Comment by ericadeahl** [comment]
@ultrasaurus 
I made a vector version of the logo with 17 stars, using the specified blue. I'll send you the svg file. Used a modified version of this icon, which should be purchased: http://thenounproject.com/term/handshake/2171/
![midas_logo_60p](https://cloud.githubusercontent.com/assets/5911280/5689262/e3ef711c-9816-11e4-8f46-f0790a427939.png)
![midaslogo_150p](https://cloud.githubusercontent.com/assets/5911280/5689317/bd24d508-9817-11e4-9645-d4cd20580606.png)

**Comment by polastre** [comment]
I love it!  Except for that gold... just seems to clash. Maybe we look for another color or (gasp) just use gray/black?

**Comment by ultrasaurus** [comment]
I do think the gold would look better with the original blue, but I would guess @ericadeahl was matching the Midas blue.  Ideally we would take a more holistic approach to the design.  I agree with @alwaysbrightblue that less variables would make a lot of sense.  For now, I think this could be a nice step forward.

**Comment by ultrasaurus** [comment]
Here's a snapshot in context:

![image](https://cloud.githubusercontent.com/assets/41906/5703833/4d380e4e-9a20-11e4-96fa-b1386f09a936.png)

I think the home page looks better with the darker blue (see earlier screenshot), but I don't want to make that kind of chage piecemeal:

![image](https://cloud.githubusercontent.com/assets/41906/5703842/5f39eea0-9a20-11e4-9ec4-34bb6a319f48.png)
