### ISSUE TITLE
As a user, I should not be able to create multiple accounts with the same email address

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#377]
I think this is possible wiht MyUSA.  Even if we get a new token (for example if someone has deleted their MyUSA account and then auths with a new one), we shouldn't create a second account with same email.

**Comment by dhcole** [comment]
I tested creating by users with local authentication and cannot create users with the same email address. If this is still happening, it must be related to another authentication method. 

Blocked upstream from testing MyUSA by 18F/issues#536

**Comment by cpapazian** [comment]
@dhcole, @ultrasaurus: @yozlet changed the encoding on our database and we were able to approve your application, so you should be unstuck. waiting for a fix so this doesn't happen again for new deploys before closing the task.

**Comment by dhcole** [comment]
Thanks @cpapazian and @yozlet, for the fix and letting us know!
