### ISSUE TITLE
when I click the share link, I should not need to have my browser configured to handle mailto

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#412]
For everyone who uses gmail, this is confusing -- mailto handlers are not configured by default.  This should open a dialog box with three text fields:
- to (comma delimited field for who they want to share with)
- subject
- a text edit field with the information that would be sent via email, so people can add a note at the top if they want.

**Comment by dhcole** [comment]
Less of an issue as Chrome now sets this up by default when users log into their accounts... building user-to-user messaging like this, or worse, allowing users to email non-users from our servers (the alternative to mailto links) is a pretty big spam vector and a problem I'd much rather delegate to users and their email clients than build into our system. Closing based on that and not hearing this as a priority. If you disagree, please feel free to reopen and continue the discussion.
