### ISSUE TITLE
As a user, I can't see my task, when other people have also signed up for it

### ISSUE THREAD

**Issue by phirefly** [18F/midas#451]
When more than one person responds to a task, the task longer shows up in a person's profile as an assignment.

**Comment by DavidEBest** [comment]
Can't duplicate on midas-dev. When reporting an issue, it would be helpful to know which server was displaying the issue, the steps to reproduce, and (if possible) links to the page that shows the issue.

To try and recreate the issue on https://midas-dev.18f.us, I:
1. Logged in with my primary account. (https://midas-dev.18f.us/profile/2)
2. Volunteered for a task (https://midas-dev.18f.us/tasks/64)
3. Checked that the task was visible on my profile.
4. Logged out.
5. Logged in with a secondary account (https://midas-dev.18f.us/profile/84)
6. Volunteered for the same task.
7. Checked that the task was visible on my profile.
8. Logged out of the secondary account, and logged back in with my primary account.
9. Checked that the task was visible on my profile.

The task was visible on my profile (under 'Opportunities Volunteered For') every time I checked.

Does my procedure match your own? Can you verify that the issue still exists?

**Comment by ultrasaurus** [comment]
This might be only for the "assigned" state
