### ISSUE TITLE
Select2 is missing asset in production

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#458]
Steps to reproduce:
1. Go to /tasks
2. Click [+ Opportunity]
3. Fill in "What problem are you trying to solve?" and click [Next]
Results:
![image](https://cloud.githubusercontent.com/assets/41906/5583073/dbf167a0-9027-11e4-8136-5846db0f7a11.png)

midas-0.0.26.js:325 GET http://localhost:1337/prod/css/select2.png 404 (Not Found)
midas-0.0.26.js:325 GET http://localhost:1337/prod/css/select2-spinner.gif 404 (Not Found)

**Comment by ultrasaurus** [comment]
This appears to be broken again

**Comment by dhcole** [comment]
Where are you seeing this? I don't see the issue locally, on dev, or on production:

![screen shot 2015-02-10 at 11 49 28 am](https://cloud.githubusercontent.com/assets/170641/6131566/e5063096-b11a-11e4-821d-80adb2cf47d8.png)


![screen shot 2015-02-10 at 11 48 42 am](https://cloud.githubusercontent.com/assets/170641/6131554/d4553d6e-b11a-11e4-9735-d5d9c612a78c.png)


![screen shot 2015-02-10 at 11 47 36 am](https://cloud.githubusercontent.com/assets/170641/6131535/af588f0c-b11a-11e4-886c-cc8fee163721.png)

**Comment by ultrasaurus** [comment]
was seeing on midas-dev, but appears to be fine now.  Closing this.
