### ISSUE TITLE
newrelic config key should be a chef attribute

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#462]
So we can include in an automated deploy

**Comment by dhcole** [comment]
@DavidEBest Can you bring me up to speed here? Is this done? I see this unmerged PR: https://github.com/18F/midas-cookbook/pull/7 Is that ready to go?

**Comment by DavidEBest** [comment]
@dhcole It should be. I didn't realize it was still open. I went ahead and made the syntax tweak that Sarah suggested.
