### ISSUE TITLE
When I submit a new opportunity, I should be able to save as draft...

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#465]
should be able to "save as draft" at any point in the workflow (after something has been filled out)
And Draft state should appear in "Change Opportunity State" dialog

related to https://github.com/18F/midas/issues/467

**Comment by dhcole** [comment]
Who should have the ability to change the state out of draft? Task creator or admin only?

**Comment by ultrasaurus** [comment]
That will need to be a config option -- by default should be task creator OR admin.  But open opps, wants admin only publish

**Comment by dhcole** [comment]
Ok, we need two config options, right?

1. `taskState` which is the default task state, `open` or `draft`
2. `draftAdminOnly` which is a `true` or `false` for whether only the admin can change the draft state

2) seems like it's somewhat complicated... After an admin moves it out of draft, can the creator put it back into draft? If so, does the admin need to move it back to open, or can the creator do that?
