### ISSUE TITLE
when I go to my profile, I should see the whole profile URL

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#469]
When I go to my profile, the URL shows:  https://midas.18f.us/profile
but it is the same as https://midas.18f.us/profile/3  (which is what is included in the email when I share my profile) 
It should show the full URL, so I know what the URL is if I want to tell other people without using the share button

**Comment by polastre** [comment]
You could, instead, make the profile URL something like `/profile/polastre` so that it is more human readable.  Just an idea.

**Comment by ultrasaurus** [comment]
@polastre if we want to change the URL, that would be a separate issue.  This issue represents the fact that I already have a full URL, I just can't see it unless I share my profile with someone via the share button.
