### ISSUE TITLE
As a user, after I sign up for a task, I should be prompted to write something that will be posted in the discussion

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#470]
After someone signs up, a dialog box would appear (with a close box) that says:

Thank you for signing up for this opportunity.  Judy Smith will be notified that you are interested and will get in touch with you.  It might be helpful for you to write a bit about why you are interested and any relevant experience.  
[  TEXT BOX ]
This will be posted on the discussion.     [ Submit ] [ Not now ]

**Comment by dhcole** [comment]
This seems stale. We're currently working on after sign-up as a redirect to fill out more details in the profile. Can't really do both, and participants and creators are now CCd on the same email, so they have a chance to talk directly through that.
