### ISSUE TITLE
As a user, after I sign up for a task, if my profile isn’t filled in, I should be reminded to do so

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#472]
The profile needs a name for the person to show up in the task, so we want to nudge someone to fill in their name, plus it will be nice for the task creator to know who they are.

At this point, we don't want to do anything that will dissuade them from signing up for an opportunity, so this should just be a friendly reminder.

"Please fill in your name, something about yourself, and upload a photo if you've got one."

(we should actually look at what is filled in and not filled in and change the text accordingly)

**Comment by ultrasaurus** [comment]
per @LisaLNelson name should be required before we complete the sign up process & send a notification

**Comment by dhcole** [comment]
@ultrasaurus how do you want to layout the sign up form with name included?

- [ ] ![screen shot 2015-01-15 at 6 37 43 pm](https://cloud.githubusercontent.com/assets/170641/5769150/af98770a-9ce5-11e4-97ea-814a90a87385.png)

- [ ] ![screen shot 2015-01-15 at 6 38 03 pm](https://cloud.githubusercontent.com/assets/170641/5769151/b3813b9a-9ce5-11e4-8c18-df9ddfbfbe8b.png)

**Comment by polastre** [comment]
I like the first one, although I think the placeholder should say "Full Name" or "First and Last Name"

**Comment by ultrasaurus** [comment]
I like the first one too.  Agree with Joe's comment that it should say "Full Name"  -- not everyone has a first and last name -- most Americans do, but you don't actually need to be an American to be a federal employee :)

**Comment by dhcole** [comment]
Resolved by #583
