### ISSUE TITLE
As a user, I should be able to send another user a message (like Facebook)

### ISSUE THREAD

**Issue by LisaLNelson** [18F/midas#473]
Users should be able to contact each other directly by sending a private message. The recipient will then be able to see the message when logged in.

On profile page, have a button that opens a text box to fill in a message that would then be emailed to the user.

**Comment by polastre** [comment]
Would it be okay if we let someone enter their message (like Facebook) and then it sends the person an email?  The reply-to is then originator's email address, so you can just hit reply in your email.  This would be a lot easier, probably provide a lot of the same functionality, and would let us test how much users actually use this functionality.

Net net: building a messaging system is _hard_.

**Comment by ultrasaurus** [comment]
Actually I was thinking of an implementaton like @polastre suggests too.

**Comment by dhcole** [comment]
Building a messaging system can be a very messy problem... but we're discussing a feature to allow users to opt in to displaying their email addresses to other users here: #782 

Closing this thread so we have one place for the conversation.
