### ISSUE TITLE
schema isn't automatically created anymore

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#475]
Would be nice if ```make init``` could work without mucking with config files...

The [Sails deployment guide](http://sailsjs.org/#/documentation/concepts/Deployment?q=overview) says: "create the database on the server and then run your sails app with migrate:alter locally, but configured to use the production server as your db. This will automatically set things up."

One option is to check in our schema and load it as part of ```make init ```

**Comment by brandtheisey** [comment]
I believe this is because config/models.js now contains migrate: 'safe' due to something related to our postgres fork.

**Comment by ultrasaurus** [comment]
yeah, but it if I do "sails lift" and hit the server, the schema will be auto-created, so I'm not sure wht make init doesn't do that (which seems to run in development env if the console output is correct)

**Comment by DavidEBest** [comment]
Running sails lift shouldn't create the schema with migrate:safe enabled.

**Comment by ultrasaurus** [comment]
@DavidEBest is correct. I must have changed ```config/models.js``` to ```migrate: 'alter'``` to get the database schema created

**Comment by brandtheisey** [comment]
Well color me confused now.
My backup up and restore from prod run today contained deletedAt columns and imported as expected. 

Dropping and recreating the public schema and lifting sails with an empty schema and migrate alter worked with no errors on my VM.

This is all the opposite of how it worked yesterday and this morning. Maybe there was a glitch in my original backups? Regardless, it appears to work as expected and sails lifted. NOW I can test.

**Comment by brandtheisey** [comment]
After testing this morning, I've found that something was broken about my initial backup that started this problem for me. 

But with a clean back up and migrate alter I've been able to:
1) repeatedly lift sails with an empty schema and have the tables created
2) repeatedly restore my back up with production data and lift sails

At this point, I am ready to write off the issues down to a PEBKAC on my end.

**Comment by ultrasaurus** [comment]
since @brandtheisey and @DavidEBest and I have been testing with 'alter' and it seems robust, we propose to check it in with that setting.  In production, that config should be ignored.
