### ISSUE TITLE
As an admin, the number of task creators should be correct

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#486]
We don't have 19 task creators on midas.18f.us -- we only have about 7, maybe 9 at the most, but the admin dashboard shows 19:

![image](https://cloud.githubusercontent.com/assets/41906/5707132/1c4a5fb0-9a3b-11e4-87e5-c6279738f6c0.png)

**Comment by dhcole** [comment]
Should this count include disabled users who have created tasks, or only currently enabled users? Unlike #485, it seems like for counting tasks, it's worth including disabled users, but wanted to confirm.

**Comment by ultrasaurus** [comment]
I agree with should include disabled users

**Comment by dhcole** [comment]
Could I get admin access to this instance of Midas?
