### ISSUE TITLE
As a particpant, I would like to see an Opportunity page with clearer information

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#513]
Feedback
- repetition in top left and lower narrative description confuses people
- the task creator seems to be very important to propective collaborators, so it should be more prominent
- consider 2 columns, rather than 3 (little box with Likes & tools creates strange negative space)

ideas: 
* https://github.com/18F/midas/issues/118
* https://github.com/18F/midas/issues/177
* https://github.com/18F/midas/issues/311

**Comment by brandtheisey** [comment]
In a sort of related note about the negative space, super short descriptions (1 to 2 lines) create a great deal of blank space on the project page. 
![projectwhitespace](https://cloud.githubusercontent.com/assets/7915386/6738021/b19b4424-ce45-11e4-8bbe-fcf81643eb2c.jpg)

**Comment by GailSwanson** [comment]
Updated layout.
![task detail](https://cloud.githubusercontent.com/assets/12940398/9984698/4b3f6f82-5fe2-11e5-9333-8ab38f31853e.png)

**Comment by ultrasaurus** [comment]
what about putting this stuff in the right column?
![image](https://cloud.githubusercontent.com/assets/41906/10004289/f401bf98-607e-11e5-8e08-1d6346394334.png)

**Comment by ultrasaurus** [comment]
Also, from the user research, people sometimes pick an opportunity based on the creator / requestor... whereas I think the progress is much less frequently referenced.

**Comment by GailSwanson** [comment]
I wanted to keep the Requestor near the top to keep it prominent, as you have pointed out, and I didn't want it to get lost below the action panel. How would you feel about putting the requestor at the top in a revised way and the progress and participants below the action panel. They are both less germane to the user's goal when viewing a task.

**Comment by GailSwanson** [comment]
Redesigned task edit screen, now in sync with the creation page.
![task edit](https://cloud.githubusercontent.com/assets/12940398/10032353/31452a7e-6148-11e5-9c82-a28b11d9390b.png)

**Comment by ultrasaurus** [comment]
I like this direction!   When viewing the task/opportunity, would pariticpate be next to the requestor on the right?

**Comment by dhcole** [comment]
@jeremiak just noting this includes the estimated completion date, which is currently not on the task edit page.

**Comment by GailSwanson** [comment]
Made some layout changes:
Moved participants and progress data to right rail under action panel
Moved Participant to top right of main content panel allowing wider area for headline.

**Comment by GailSwanson** [comment]
Can you reduce the task description font size to 16px? That will help with the layout

**Comment by GailSwanson** [comment]
This should clarify.

![task detail20150924](https://cloud.githubusercontent.com/assets/12940398/10075808/81b728b2-629d-11e5-97c8-2dd16c05bfce.png)

**Comment by jeremiak** [comment]
Thanks @GailSwanson!

**Comment by GailSwanson** [comment]
Made some edits to the task edit view to add in the informative bits that we put in the task creation page. My thought is that a user can view the hint copy by tapping the info icon. I can mock that up if you like, or I'm good with a standard looking interaction for that.

![taskedit_20150924](https://cloud.githubusercontent.com/assets/12940398/10076537/a2c17da6-62a1-11e5-99b7-274c46a3f348.png)

**Comment by GailSwanson** [comment]
@jeremiak Can you massage the spacing between elements to more closely reflect the mockup? Having larger space between each label-field group and small space between the label and the field largely helps users understand the form. 

Also, please change "title" to "Headline"

**Comment by jeremiak** [comment]
@GailSwanson You got it, I'll give you a ping when that's wrapped up.

**Comment by jeremiak** [comment]
@GailSwanson here's the latest with your feedback:
![edit-task](https://cloud.githubusercontent.com/assets/780941/10106276/b434125c-6381-11e5-85e7-beec9f83204b.png)

**Comment by GailSwanson** [comment]
Let's ship it.
