### ISSUE TITLE
Move sails-postgres to NPM

### ISSUE THREAD

**Issue by dhcole** [18F/midas#526]
Currently, we depend on 18F/sails-postgres as an external dependency. We should move this to NPM. Needs to link to the `softdelete` branch, which we can do [like this](https://docs.npmjs.com/files/package.json#github-urls).

Need to update the following:

- [ ] package.json
- [ ] install.md
- [ ] 18F/midas-cookbook

**Comment by ultrasaurus** [comment]
@dhcole this is great.  After changing ```package.json```, I assume a single npm install would install all packages into the midas node_modules folder, right?

this might also help @brandtheisey with his no-internet-access install.

**Comment by dhcole** [comment]
Yea, that's right. `npm install` would download all of the packages and install them in `/node_modules`. In theory, you should be able to copy the `/node_modules` directory to another server and run the application without `npm install`.
