### ISSUE TITLE
When I sign up for a task, I should be cc'd on the notification

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#527]
and we should adjust the wording...

**Comment by kategarklavs** [comment]
@ultrasaurus Would one of the email templates I created work for this? If not, happy to write a new one.

**Comment by ultrasaurus** [comment]
Draft wording:


Subject Line: Thanks for your interest in [task name here]

Hi [user’s name],

We just received your request to claim [task name here]. Thanks for your interest in this opportunity – we’re glad you’d like to help out!

During the next few days, we’ll review your profile (and may get in touch with you) to ensure you’re a good fit. If your skills and interests match what we’re looking for, we’ll assign you the task and send a confirmation email.

In some cases, several qualified candidates might express interest in a task. If you’re not chosen to complete it, don’t fret: our selection of available tasks is always changing. Check back often to see the latest selection.

Finally, we know you’re excited to get involved, and we also know that some scheduling conflicts can’t be avoided. If you’re unable to complete a task, please reach out right away to [task creator’s name], who is CCd on this email. 

Thanks again,

The ____ team

**Comment by kategarklavs** [comment]
Yesss!

**Comment by ultrasaurus** [comment]
fixed with:  https://github.com/18F/midas/pull/535

**Comment by ultrasaurus** [comment]
fixed with https://github.com/18F/midas/pull/535
