### ISSUE TITLE
setup travis for 18F fork of sails-postgresql

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#529]
https://github.com/18F/sails-postgresql

**Comment by dhcole** [comment]
Ok, should this and https://github.com/18F/sails-postgresql/pull/2#issuecomment-71944755 take priority over the drafts work?

**Comment by dhcole** [comment]
I got the tests working, but I'd say let's hold off on travis for now, since we shouldn't be doing much development in that repo. Let's leave this open for a future milestone.

**Comment by polastre** [comment]
FWIW, we've been using SnapCI and its much more reliable than Travis.

**Comment by dhcole** [comment]
Moved ^
