### ISSUE TITLE
Anyone should be able to save an opportunity as draft

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#536]
Right now the default state is configurable, but new task creators should be able to click "Save as Draft" at any point during the new opportunity workflow

**Comment by ultrasaurus** [comment]
Since the back end already supports saving a draft, adding this button should be straightforward.

**Comment by ultrasaurus** [comment]
if I hit the back button, then I no longer see the "Save Draft" button
Also, when it is configured, so the user can't publish, then it should not show the "Create" button at the end -- I think it would make more visual sense if the "Save Draft" button was right-most  (but to the left of the Create button if it is visible)

**Comment by dhcole** [comment]
Closing as this will be superseded by on-going work to redesign the task creation workflow by @GailSwanson
