### ISSUE TITLE
I should not be able to sign up for a draft task

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#538]
Drafts are only visible for the task creator and the admin, so this doesn't cause any real problems, but it is confusing.

As an admin I see:
![image](https://cloud.githubusercontent.com/assets/41906/6010154/fef1eb80-aae4-11e4-8143-d738a8c2e539.png)

As a non-admin task creator I see:
![image](https://cloud.githubusercontent.com/assets/41906/6010162/100284c0-aae5-11e4-997a-4bdb4bd917dd.png)

I think we should just hide the "I'm in" button (or "Volunteer" in vanilla Midas) when in Draft mode.

**Comment by dhcole** [comment]
Should we also hide that for task creators? Would they ever volunteer for their own tasks?

**Comment by ultrasaurus** [comment]
yeah, whether is is draft or not, it doesn't make sense to sign up for your own task!
