### ISSUE TITLE
For CRM intergration, automated sync with CSV export of user data

### ISSUE THREAD

**Issue by dhcole** [18F/midas#544]
The Open Opportunities team would like to sync user data with their CRM. Seems like the easiest way to do this is to generate a CSV of user data. Second step would be to run that export on a scheduled process (monthly) and email it to the CRM team.

**Comment by dhcole** [comment]
Holding on this until we hear more from OCSIT

**Comment by sefk** [comment]
See pull request #691.

![task_export](https://cloud.githubusercontent.com/assets/621565/6960040/b556ab38-d8d3-11e4-90fe-092f2944ebff.png)

![task_excel](https://cloud.githubusercontent.com/assets/621565/6960043/ba0650f2-d8d3-11e4-85c2-8613b5bd7abe.png)
