### ISSUE TITLE
CrowdWork (windows) takes forever to start ORM on application start

### ISSUE THREAD

**Issue by brandtheisey** [18F/midas#546]
So, I think I have narrowed down the issue with my upgrade to https://github.com/balderdashy/sails/issues/1402.

I'm currently timing a sails lift to see if it ever comes up. It's at just over 6 minutes. Also, the solution in the above issue (making config/models.js say migrate) doesn't work for me.

To me this suggests i have an issues with my sails-postgresql fork, more than the sails app specifically. Thoughts?

**Comment by ultrasaurus** [comment]
@brandtheisey I just merged in the new way of creating the database schema, so we shouldn't ever use sails migration.  Can you try with the latest devel branch?

**Comment by dhcole** [comment]
How about ruling postgres out completely by using the memory db?

change https://github.com/18F/midas/blob/devel/config/models.js#L9 to `'memory'`

**Comment by brandtheisey** [comment]
Changing it to memory made it come right up almost instantly.

**Comment by dhcole** [comment]
Definitely pg-related! Do you have access to query the DB directly? Can you see the structure and make sure the tables look set up correctly? Does `make init` work?

**Comment by brandtheisey** [comment]
I can't run make at all for the moment, I'm still trying to figure out what to do about that.

I'm going to rebuild my sails postgres fork and try again. 

Of note the command after "starting the ORM" (where it hangs in the orm hook) is an async.each command which i may need to upgrade that package as I have a vague memory of getting a message about async.

**Comment by ultrasaurus** [comment]
well, now that the schema is checked in, you could manually load ```schema/current.sql``` like is done in ```./tools/postgres/init.sh``` without actually needing to run that who script

**Comment by brandtheisey** [comment]
I rebuilt the sails postgres fork and now get : 
FATAL ERROR: CALL_AND_RETRY_2 Allocation failed -- process out of memory

after it runs for about 13 minutes.

**Comment by brandtheisey** [comment]
Changing the migrate setting to safe instead of alter fixes this. Also, this CW now runs in production mode so the load process is different.
