### ISSUE TITLE
If File table is too large, sails 10.5 won't lift

### ISSUE THREAD

**Issue by brandtheisey** [18F/midas#561]
I believe I've finally found the issue that was preventing my upgrade to Sails 10.

Restoring a dump of my production data to my local environment prevented sails from lifting (the same behavior I see on Production). A clean fresh schema allows sails to lift fine.

In reviewing my production dump, I noticed that the file table was excessively large, so I dropped the file table and sails lifts with my otherwise production data.

Using the size column as a guide to how much data was in my table, I had 77,000,000+. which doesn't seem like it should be enough to crash the server, but in 10.5 it seems to be.

**Comment by dhcole** [comment]
Tracked in #589
