### ISSUE TITLE
new relic configuration not working on midas-dev

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#567]
is ```config/settings/newrelic.js``` used?
our settings are in ```config/local.js```

**Comment by dhcole** [comment]
Yes, settings/newrelic.js is the main configuration file for new relic. local.js is a server-specific override. eventually, local.js should go away and we should use env vars in rewrelic.js, but i didn't make that change yet to avoid too many moving pieces -- our cook-book already expects to be working with local.js

**Comment by ultrasaurus** [comment]
re-opening with more clear title -- we need to figure out why this isn't working on midas-dev.18f.us

**Comment by dhcole** [comment]
Closed with #571
