### ISSUE TITLE
New text for Opportunity Assigned email

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#579]
In the following text will need to use "localized" versions of Task -> Opportunity, TaskOwner -> Opportunity Creator, etc.

```
To: Participant
CC: Task Creator
Subject Line: You’ve been selected for [task name here]! 

Hi [user’s name],

Great news: You’ve been selected to complete “[task name here]!”

Before you get started, please review the Opportunity details: http://openopps.digitalgov.gov/tasks/12

Have questions about what you need to do? Post them to the discussion — directly below the Opportunity description — for the quickest response. 

If you’d like more in-depth guidance, feel free to reach out to the Opportunity Creator (CC’d on this email) to set up a phone call or video chat.

Thanks again for joining us: We’re excited to have you on the team! 

Best,

The Open Opportunities team
```

**Comment by dhcole** [comment]
@ultrasaurus Who should receive this email? There is not a concept of assigning a task to a particular person, just setting it as 'assigned'. Should all volunteers (anyone who hit I'm In) get this? Do task owners need a way  remove volunteers?

**Comment by ultrasaurus** [comment]
Yes, everyone who is signed up should get this email.  Task owners and admins can remove participants (volunteers) by editing the task (at the bottom).

**Comment by dhcole** [comment]
If there are multiple volunteers assigned, do you want a personalized email to go to each of them, or should it be one email with all volunteers in the "to" line?

If individual emails, should the owner be cc'd on all of them?

Currently, there isn't a mechanism for separate emails to multiple people on one notification, so if you want the first option, we'll need to build that to support this.

**Comment by ultrasaurus** [comment]
see discussion in https://github.com/18F/midas/pull/601

**Comment by ultrasaurus** [comment]
looks good!
