### ISSUE TITLE
Refine how madlibs text is displayed on the opportunity show screen

### ISSUE THREAD

**Issue by Chessen** [18F/midas#58]
We can refine how the data is shown so that the paragraph flows better. No reason why what the volunteer sees has to exactly match what the requestor enters. 

Related to #56 

Currently reads:
I need [personnel needed tag] to work on an opportunity about [topic tag]. 
The following skills are [required/not required tag] to complete this opportunity: [skill tag] . It will require [estimated hours required] of  [time commitment tag] work, and must be completed within [deadline tag]. The volunteer(s) [work location tag]

Recommended flow:
We need [personnel needed tag] to work on an opportunity about: [topic tag]. 
The following skills are useful and [required/not required tag] to complete this opportunity: [skill tag]
The opportunity will require [estimated hours required] of  [time commitment tag] work, and must be completed within [deadline tag]. 
The volunteer(s) [work location tag]
ClassNet access [is/is not] required to complete this opportunity. 
 
[work location tag] will depend on whether the requestor selected required or not required for a location.
 If requried, it should read: must be located at [location tag] 
If not required, the text should read: can be located worldwide.

Can we also put a time stamp that shows when the opportunity was created? Without it, there is no context for what the deadline tag relates to. Something like: This opportunity was created on [date]

Related to #56 and #59

**Comment by jeremiak** [comment]
So this card jumped forward in waffle because I accidentally mentioned it in a PR. Not sure where it goes, so moving to the top of the backlog? Sorry ><
