### ISSUE TITLE
Add tests for access to tasks

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#582]
I think we just missed this when we added opportunity states.  To repro:
1) set opportunity state to "Assigned'
2) logout
3) go to opportunity URL 
results: see blank page
expected: see opportunity details

**Comment by ultrasaurus** [comment]
This appears to be a serious regression:
![image](https://cloud.githubusercontent.com/assets/41906/6193151/4b2d379e-b36d-11e4-9bfc-af3e514e4b52.png)

**Comment by dhcole** [comment]
Needs tests
