### ISSUE TITLE
Sometimes, file upload data is being stored as JSON

### ISSUE THREAD

**Issue by dhcole** [18F/midas#589]
Found this on the dev server. Profile photos were being stored in the file table as text, in what looks like json-encoded binary data. Needless to say this was causing the table size to balloon. Subsequent uploads went through fine. Not sure of the root cause yet. One way to just avoid the problem completely would be to not store files in the DB.

cc @brandtheisey Check to see if you have any records in your file table with large binary fields. Note: the size field reflected the size of the image before it was uploaded, which is when it blew up. So I was seeing records with a few kb in `size` but the actual binary data was several mb.

**Comment by brandtheisey** [comment]
The sum of my size field is currently 911K and the database seems to report the size of that table as 63mb.

**Comment by dhcole** [comment]
Yea, I bet you have the same issue going on. I can't reproduce it, and it only happened on our development server, but it happened recently. Going to prioritize moving off DB file storage this week to just avoid the issue altogether.

**Comment by brandtheisey** [comment]
"{"0":123,"1":34,"2":48,"3":34,"4":58,"5":50,"6":53,"7":53,"8":44,"9":34,"10":49,"11":34,"12":58,"13":50,"14":49,"15":54,"16":44,"17":34,"18":50,"19":34,"20":58,"21":50,"22":53,"23":53,"24":44,"25":34,"26":51,"27":34,"28":58,"29":50,"30":50,"31":53,"32":44, (...)"

This is what my data field looks like.

**Comment by dhcole** [comment]
Free sticker if you can figure out why that's happening!

**Comment by DavidEBest** [comment]
This could be related to the Sails .9 to Sails .10 migration. The default body parser changed from the Connect multipart middleware to [Skipper](https://github.com/balderdashy/skipper). I did have to make a few changes in FileController.js to work with the new body parser.

**Comment by dhcole** [comment]
I can reproduce it by the following:

- start server
- add profile photo (size is normal)
- stop server (size is still normal)
- start server (image is converted to json, size blows up)

Something seems to be happening when sails boots...

**Comment by dhcole** [comment]
Only happens in `NODE_ENV=development` so likely caused by `models.migrate = 'migrate'`. This makes this not a risk for production and explains why we've only seen this on the development server.

**Comment by brandtheisey** [comment]
I may be missing something but is there anyway to recover files thats have been converted to this?

My production environment runs in development mode and all my production files appear to have been converted. 

The raw dump for inserts looks pretty standard:
'\x7b2230223a3235352c2231223a3231362c2232223a3235352c2...'
but none of the functions I know to decode are producing usable files, with or without the leading \x.
