### ISSUE TITLE
as a participant, I should get an email when task is assigned

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#627]
taskAssigned emails don't seem to be going out on midas.18f.us

```
    'taskAssigned': {
      layout: 'default',
      template: 'taskAssigned',
      subject: 'You’ve been selected for <%= task.title %>!',
      templateLocals: { },
      layoutLocals: { }
    },
```

**Comment by dhcole** [comment]
This is verified working on the dev server. Looks like the production server is just behind on deployments:

https://github.com/18F/midas/compare/master...devel

This alert is set up in subsequent commits.

**Comment by ultrasaurus** [comment]
@dhcole I thought that before the in 0.2.2 label, sorry I misread the commit log!
