### ISSUE TITLE
I should never see "We need 'no people yet assigned' ..."

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#629]
I thought we fixed this bug a while back...

![image](https://cloud.githubusercontent.com/assets/41906/6509660/b3ff36d4-c315-11e4-8676-c85cc79e9095.png)

**Comment by ultrasaurus** [comment]
I'm going to manually fix this on the dev server, since I'm doing a demo today, but should be reproducible, since we just created this data from scratch

**Comment by ultrasaurus** [comment]
FYI: when editing I see:
![image](https://cloud.githubusercontent.com/assets/41906/6509687/e7f9bc0c-c315-11e4-8314-b43a4620c803.png)

**Comment by dhcole** [comment]
This seems to have been fixed along the way. 

![screen shot 2015-04-09 at 4 01 24 pm](https://cloud.githubusercontent.com/assets/170641/7075669/d527f526-ded1-11e4-9e23-d7171a2de7d8.png)
