### ISSUE TITLE
A process for users to apply to opportunities and for requestors to accept them

### ISSUE THREAD

**Issue by jhinton** [18F/midas#64]
Opportunity Owner should be able to privately select the Volunteers they’d like to have perform the opportunity posted.

This selection process should not be visible to anyone other than the Requestor and volunteer. (In other words, in the app expressing interest should be known only to the requestor)

As a Opportunity Owner should be able to see privately a list of all Volunteers who have expressed interest.

After the requestor completes their approval, only then can the volunteer can officially join the opportunity as a contributor.

Midas should be capable of providing metrics to demonstrate how many volunteers express interest in opportunities and how many are selected.

**Comment by ultrasaurus** [comment]
Now a task owner, can remove a volunteer and we've added an "assigned" state -- this process is available in public.  We're deferring all "private" systems until the public system is working well.
