### ISSUE TITLE
Create a github page

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#649]
Target audience:  prospective contributors or people who are learning about Midas because they might want to install it themselves for use in their company or community

Draft Content:

### Midas is a “Kickstarter for people’s time.” 

Here’s how Midas works: You come up with a great idea that would help your workplace, but you and your coworkers don’t have the skills to execute it. Rather than bringing in a contractor, you can post your project idea to Midas, where other people within your organization can see it and then work on it, if they’d like. 

Midas is currently in active use [inside the US federal government](https://18f.gsa.gov/2014/07/16/midas-a-marketplace-for-innovation-in-government/) as the software that drives the [Open Opportunities](http://www.digitalgov.gov/join-digitalgov/open-opportunities-in-digitalgov/) program, which connects people from across and within government agencies to collaborate on projects. Open Opportunities validated the model using WordPress and a Lean Startup "concierge" approach, with people from over 50 government agencies, completing over 100 projects, ranging from 1 hours tasks to working part-time for 3-6 months.  Open Opportunities moved to Midas in October 2014, and is available for all federal employees [here](https://midas.18f.us/). Midas was originally developed by the Department of State and is being piloted there, specifically for foreign service officers.

Our Goal: to foster innovation across team boundaries by connecting individuals who identify challenges and then work collaboratively to implement solutions.

Midas can benefit all organizations, but it’s especially useful for those with distributed teams and whose employees have diverse skill sets.  Using Midas, you and your colleagues can work on projects together, get to know each other better, and develop skills you don’t use as often as you’d like.

How you can help:
* Use our [test server](https://midas-dev.18f.us/) and write up [issues](https://github.com/18F/midas/issues)
* Join our [Google Group](https://groups.google.com/forum/#!forum/midascrowd) and introduce yourself, please ask any general questions here -- how the product is supposed to work, usability issues, technical questions, whatever you want to know, we want to hear about.  If you are interested in using Midas for your organization, let us know.
* Read our [Contribution Guide](https://github.com/18F/midas/blob/devel/CONTRIBUTING.md) -- everything you do with us is a contribution to the public domain, there are also some tips for getting started
* If you are a developer, [install](https://github.com/18F/midas/blob/devel/INSTALL.md) the software for development
* Dive into our [help wanted issues](https://github.com/18F/midas/labels/help%20wanted) -- there are both dev and design opportunities there

**Comment by ultrasaurus** [comment]
based on a first draft by @melodykramer

@dhcole @imf @moncef @louh @ LisaLNelson  interested in your feedback too!

**Comment by ultrasaurus** [comment]
thinking of using this default style for starters:
![image](https://cloud.githubusercontent.com/assets/41906/6715080/64686b2e-cd59-11e4-82eb-00d8467eb928.png)

**Comment by melodykramer** [comment]
It would be great if there were visuals and/or a video showing someone walking through Midas. Also maybe a testimonial or two from both users of the site and the groups that post opportunities.

**Comment by dhcole** [comment]
Love the idea of making this easier for people to pick up. Can this need be met by updates to the [readme](https://github.com/18F/midas/blob/devel/README.md) or [contributing guide](https://github.com/18F/midas/blob/devel/CONTRIBUTING.md)? As a user of other open source projects, I tend to just prefer a well-written readme on the github project page rather than a separate pages site.

**Comment by louh** [comment]
I like the idea of a light weight pages site to introduce someone to Midas. I'm thinking that a common use case is someone at the level of a non-technical PM, who might understand Midas better if they weren't distracted by extra GitHub UI. And because tasks and projects are not necessarily technical in nature, you want non-technical people to understand how a system like this might be relevant for their organization and for any kind of project.

You could also possibly kill two birds with one stone by having a Markdown-formatted README get piped into a generator that builds the site, if you so choose to implement it that way...

**Comment by ultrasaurus** [comment]
I like that idea.  @dhcole suggested a similar thing with an index.html that displayed the README, something like this:  http://inkwell.github.io/#63c93f26cc5663a1d7eb
(though, of course, without the broken image link)

**Comment by dhcole** [comment]
Here's a quick implementation of a static page that would be hosted at `https://18f.github.io/midas` and just pulls content from the readme: #651 

![screen shot 2015-03-18 at 4 14 41 pm](https://cloud.githubusercontent.com/assets/170641/6718528/bc7bd34c-cd8a-11e4-8c67-5c163e1c38e0.png)

**Comment by dhcole** [comment]
Opened a support request with github (their support system works over email so no link)

**Comment by afeld** [comment]
@dhcole What's the issue?

**Comment by dhcole** [comment]
@afeld Getting this error when trying to build on `gh-pages`:

> The page build failed with the following error:
> 
> The submodule registered for `./bootstrap` could not be cloned. Make sure it's using https:// and that it's a public repo. For more information, see https://help.github.com/articles/page-build-failed-invalid-submodule.
> 
> If you have any questions you can contact us by replying to this email.

It worked when I removed and added the submodule but now it's returning the same error when we push to the branch again.

**Comment by dhcole** [comment]
GitHub found that the issue has to do with a submodule of a submodule. So we're deleting submodules from this branch.

I just pushed changed that removed unnecessary files from `gh-pages`, changed the static site to pull from the `devel`branch readme, and added the video embed.

To make changes to the site going forward, just edit the readme in the `devel` branch. If you want to change the html template, edit `index.html` in the `gh-pages` branch. There is no need to sync `devel` -> `gh-pages` anymore. They're essentially different applications now.

See the current readme here: http://18f.github.io/midas/

Over to @ultrasaurus to review and close.

**Comment by ultrasaurus** [comment]
look great!
