### ISSUE TITLE
`vagrant up` fails because `git submodule update --init` times out

### ISSUE THREAD

**Issue by GabeIsman** [18F/midas#652]
I ran into this issue every time I tried, so I don't think it's intermittent. The timeout is 10 minutes. Running `git submodule update --init` manually on the box, and then re-running `vagrant provision` fixed the issue.

This appears to be the line causing trouble: https://github.com/18F/midas-cookbook/blob/devel/recipes/app.rb#L16

What's a little unclear to me though, is why this is even the right behavior. Why not just copy the src directory to the deploy directory, and then build? Why does it need to check everything out again? In fact I could imagine being pretty confused by running `vagrant up` only to discover that the code running on the newly provisioned box was not the same as the code in my current branch.

One possible solution may be a chef recipe specifically for local development which just copies the application directory to the source directory.

**Comment by ultrasaurus** [comment]
@GabeIsman We mostly use vagrant to test the cookbook, which is also used to deploy to AWS.  I'm curious do you prefer to use Vagrant for development, or did you start using it because it is first in the install instructions?   

Just want to guage how much folks are excited about Vagrant, or whether the install instructions should be modified to lead people toward what currently seems to be the more popular path of running everything locally.

Thanks for reporting these issues.  Excited to have you experimenting with Midas!

**Comment by GabeIsman** [comment]
@ultrasaurus I think I started down the vagrant path because it came first (giving me the impression that it was pretty well supported) and because I thought it be a quick and easy way to start messing around. I think vagrant is a good tool, and it's always nice when there a project has a simple way to start hacking immediately. So there is value in maintaining Vagrant-based local development flow. That said, on pretty much any project that I spend more than a day on, I end up switching to a purely local environment, because I find Vagrant to be kind of painful in some situations.

Midas also seems to have a fairly simple local environment. It took me >2 hours to get everything running smoothly (some of which was spent dealing node version issues). The instructions are clear and pretty complete. So I would definitely consider rearranging the install docs to highlight local development. A vagrant workflow makes me sort of nervous that a project has a super complex stack.

**Comment by dhcole** [comment]
We no longer use git submodules so this should be resolved.
