### ISSUE TITLE
with new database, make init fails because of psql permissions

### ISSUE THREAD

**Issue by GabeIsman** [18F/midas#654]
`vagrant up` fails because of psql permissions

Stack trace:

==> default: ---- Begin output of make init && touch /tmp/midas_init ----
==> default: STDOUT: ./tools/postgres/init.sh
==> default: Loading current schema.
==> default: SET
==> default: SET
==> default: SET
==> default: SET
==> default: SET
==> default: SET
==> default: CREATE EXTENSION
==> default: SET
==> default: SET
==> default: SET
==> default: CREATE TABLE
==> default: ALTER TABLE
...
==> default: ALTER TABLE
==> default: REVOKE
==> default: REVOKE
==> default: GRANT
==> default: GRANT
==> default: INSERT 0 1
==> default: STDERR: psql:/var/www/midas/tools/postgres/schema/current.sql:23: ERROR:  must be owner of extension plpgsql
==> default: psql:/var/www/midas/tools/postgres/schema/current.sql:1324: WARNING:  no privileges could be revoked for "public"
==> default: psql:/var/www/midas/tools/postgres/schema/current.sql:1325: WARNING:  no privileges could be revoked for "public"
==> default: psql:/var/www/midas/tools/postgres/schema/current.sql:1326: WARNING:  no privileges were granted for "public"
==> default: psql:/var/www/midas/tools/postgres/schema/current.sql:1327: WARNING:  no privileges were granted for "public"
==> default: /bin/sh: 1: ./node_modules/.bin/mocha: not found
==> default: make: *** [init] Error 127
==> default: ---- End output of make init && touch /tmp/midas_init ----

**Comment by GabeIsman** [comment]
Note that the instructions [here](http://gilesbowkett.blogspot.com/2011/07/error-must-be-owner-of-language-plpgsql.html) resolved the issue for me when I ran into the same issue running `make init` manually.

**Comment by ultrasaurus** [comment]
@dhcole these issues don't actually have anything to do with vagrant and could happen on any new install.  I actually ran into the same error when I dropped and re-created the DB on the dev server a few weeks ago.

**Comment by dhcole** [comment]
I think this should be cleared up with the switch to `npm` from `make`. If you still see it, just reopen and I'll take another look.
