### ISSUE TITLE
as a sysadmin, I'd like to see timestamps in the application log

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#660]
I can't believe I never noticed this before, but must be sails default not to output timestamps

**Comment by ultrasaurus** [comment]
looks like we can configure to use winston, which supports timestamps as an option.  SailsJS captainslog used to use winston -- possible we lost something with the recent Sails .10 upgrade

I'll give this a try

**Comment by ultrasaurus** [comment]
FYI: We used to use forever in production, which adds timestamps to the logs.

I looked at using winston for logging (which allows configuration of timestamps among other things.), it seems like a good solution, but for some reason setting the configuration in config/log.js isn't having any effect.  

Just adding a note here, since I probably won't get back to this for a few days.  Below is the approach I tried.  Seems like a nice attribute of warden to be able to configure prettier console log and add timestamps to the file where you need it more...

```
var winston = require('winston');

var customLogger = new winston.Logger({
  transports: [
                new (winston.transports.Console)({
                    'level': 'info',
                    'colorize': true,
                    'timestamp': false,
                    'json': false
                }),
                new winston.transports.File({
                    'level': 'debug',
                    'colorize': false,
                    'timestamp': true,
                    'json': false,
                    'filename': './logs/test.log',
                    'maxsize': 5120000,
                    'maxFiles': 3
                })
            ]
});

module.exports = {

  colors: false,  // To get clean logs without prefixes or color codings
  custom: customLogger

};
```

**Comment by brandtheisey** [comment]
I think there is a bug related to forever on Windows that might be the root of my issue.

**Comment by brandtheisey** [comment]
I think this is the default config I would go with. In my opinion it's the simplest and easiest to understand . This and **npm install winston --save** is all that's needed I think. Of course we'll each have to change the filename to where our log paths go, but I think if we need more we can change this later.

```
var winston = require('winston');

winston.add(winston.transports.File, {
    filename: 'application.log', 
    level: 'verbose', 
    json: false, 
    maxsize: 5120000, 
    maxfiles: 3 
});

module.exports.log = {
  colors: false, // To get clean logs without prefixes or color codings
  custom: winston
};
```
