### ISSUE TITLE
As a user of MyUSA or Midas, I should get an email telling me what Midas is.

### ISSUE THREAD

**Issue by melodykramer** [18F/midas#661]
I just tested MyUSA and signed up for Midas. After sign up, users are emailed a nice note from Midas, but the email copy currently doesn't remind them what Midas is. It could be a one sentence add, and remind users who may not immediately check their email what it is they signed up for.

I'm happy to write this copy, just wanted to check first.

**Comment by ultrasaurus** [comment]
@melodykramer we did a whole bunch of work on emails and somehow this one never made it to a github issue.  Below is a draft that @kategarklavs wrote (focusing on the on-boarding experience).  It has just one sentence about what this thing is.  Do you think it needs more?  Would love your feedback / suggested edits.



Hi [user’s name here],

Welcome to Open Opportunities! As a participant, you’ll be able to collaborate with users across different agencies and complete projects that reflect your interests. 

Before you start expressing interest in Opportunities, please complete your profile:

Write your bio: Share a bit of background information to help other participants get to know you.
Add a photo: Upload a profile picture to help other participants put a face to your name. 
List skills and topics: List your strongest skills and topics that interest you - this helps task creators match you with your ideal Opportunities.

Questions? Email us at xxxxxxxxx@xxxxxx.gov.

We’re happy to have you involved!

The Open Opportunities team

**Comment by melodykramer** [comment]
That looks great! I think that might be a different email than the one people receive who sign in through MyUSA:


midas
Welcome to midas!

Please take a moment to ensure that your profile is complete and accurate.

We are happy to have you involved!

Thanks! 
- The midas Team

**Comment by ultrasaurus** [comment]
The one you are seeing was a placeholder.  You caught the issue that we never implemented Kates nice email, but now we can queue this up to fix !

**Comment by ultrasaurus** [comment]
This should be just a text change.
