### ISSUE TITLE
As an admin, I would like to export CSV of user data

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#667]
Ideally this would be a link in the User Management panel of the admin section

**Comment by ultrasaurus** [comment]
related to: https://github.com/18F/midas/issues/544

**Comment by sefk** [comment]
See pull request #691 

![user_export](https://cloud.githubusercontent.com/assets/621565/6959998/4e16a8e2-d8d3-11e4-82f1-b2a9c0b4655b.png)

![user_excel](https://cloud.githubusercontent.com/assets/621565/6960026/8dd39d46-d8d3-11e4-94ee-8b0eb9ef6c3e.png)
