### ISSUE TITLE
As a task creator, I would like to see an introductory screen informing me of expectations

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#670]
on the /tasks page, when someone clicks [+ Opportunity], we would like an additional first step where the following text is presented

We’re glad you want to create an Opportunity! Before you continuing, please review the following Task Creator responsibilities.

As a Task Creator, I will:
* respond promptly and positively to task takers
* lay out clear and realistic deliverables
* be clear about how much time is needed to complete the task 
* define the skills needed 
* be prepared to onboard the task taker. If the task assigned is a simple one, take the time to explain it. If the task is big or long-term, be prepared to mentor the participant.

[  ]  I agree to fulfill these responsibilities as a task creator 
 (check box)

The state of the check box does not need to be stored in the database -- it would just be required to be checked before people continue to the next step

**Comment by sefk** [comment]
See pull request #697. 

![responsib](https://cloud.githubusercontent.com/assets/621565/7009296/1e2202f2-dc4e-11e4-8aa5-460b4eda83b4.png)
