### ISSUE TITLE
As a member, I would like a page where I can see other members of the community

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#673]
There's an old branch that had an initial implementation of this that might be worth checking out:  https://github.com/18F/midas/tree/feature/browse-people

The idea was that there would be a "people" tab and you could browse and search, and then people would be displayed with "cards" in a similar way to tasks.

Open to other design ideas on this.

**Comment by arena** [comment]
I'm exploring some design ideas for this. Will post a link.

**Comment by arena** [comment]
Exploration of this feature is here https://github.com/arena/midas-community-design

**Comment by ultrasaurus** [comment]
@sefK is working on this, related to #672

**Comment by dhcole** [comment]
Closed by #781
