### ISSUE TITLE
As an admin, I need a way to remove comments

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#689]
We've been discovered by a spammer...

https://midas.18f.us/tasks/67
https://midas.18f.us/tasks/68

**Comment by brandtheisey** [comment]
#679 ! But we should talk about the behavior for Topic comments before merging this.

**Comment by ultrasaurus** [comment]
@brandtheisey this is resolved with the move to flat comments, right?

**Comment by brandtheisey** [comment]
@ultrasaurus yup!
