### ISSUE TITLE
Project should have a timeline and their current progress bar

### ISSUE THREAD

**Issue by sharonlo** [18F/midas#69]
Allows project owners to specify the different steps to the project and how close the project is to completion. In addition, with each step of a project, different tasks are needed, maybe have a “Currently working on developing demoserver, looking for help to code” or “Currently working on designing demoserver, looking for help in graphic design” This way, people know immediately what’s currently being worked on in the project

**Comment by ultrasaurus** [comment]
We're adjusting our process to close icebox tasks.
