### ISSUE TITLE
If I click on a non-existant user profile link, I should get a useful error message

### ISSUE THREAD

**Issue by brandtheisey** [18F/midas#692]
Currently all I get is a blank screen and a javascript error that says "Cannot read property 'type' of undefined.

**Comment by dhcole** [comment]
It's better now: 
<img width="239" alt="screen shot 2015-09-24 at 12 25 42 am" src="https://cloud.githubusercontent.com/assets/170641/10065380/24029dd6-6253-11e5-806a-55630053d1cc.png">

Could still use a custom 404 (#149), but not unique to this route.
