### ISSUE TITLE
version number is missing from footer

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#694]
We used to have version number in the footer
![image](https://cloud.githubusercontent.com/assets/41906/7004717/95cc985a-dc24-11e4-8c63-4b93a00ed2df.png)

it is no longer there (on midas-dev.18f.us):
![image](https://cloud.githubusercontent.com/assets/41906/7004722/a42840ca-dc24-11e4-9cdb-a30e55bc1903.png)

**Comment by dhcole** [comment]
It used to show the git commit SHA. I removed this when we removed git as a dependency for running Midas. (Users should be able to download the zip file, run `npm install`, and have a working midas). If the server that built the assets does have git installed, you'll still find the latest SHA when you view source and look at the file name for the CSS or JS bundles.
