### ISSUE TITLE
New task wizard better button state handling

### ISSUE THREAD

**Issue by sefk** [18F/midas#695]
The handling of the buttons in the New Task wizard is fragile, difficult to extend, and doesn't handle edge cases well. The code in modal_wizard.js calculates the button states (visible or not, disabled or not) in separate forward/backward functions, instead it would be better to leave the flipping logic in the forward/backward functions, but to have a single function to calculate and implement button state. 

- initial button state, don't rely on view template correctly hiding "create" button
- same behavior whether or not you get to something forward or backward
- don't enable "back" from first page

This is related to issue #670.

**Comment by ultrasaurus** [comment]
:+1: this would be a helpful improvement to the system

**Comment by brandtheisey** [comment]
:+1: I like this a lot. We have a lot of one off modal code and it would be great if it was more extensible.

**Comment by sefk** [comment]
Fixed in PR #697
