### ISSUE TITLE
Update baseline nginx to latest stable version, ensure deployment scripts always look for latest stable

### ISSUE THREAD

**Issue by NoahKunin** [18F/midas#701]
Tests are showing `nginx 1.4.6`, latest stable version is `1.6.3`. 

http://nginx.org/en/download.html

Each new deploy should run an update against `nginx` to grab the latest.

**Comment by dlapiduz** [comment]
@NoahKunin I am not sure it is a good idea to just grab the latest nginx automatically without testing it first. Because of the way we are doing autoscaling we could end up with the site down if there is any compatibility issue.

That said 1.4.6 is pretty old, going to rebake the AMI with 1.6.3.

**Comment by ultrasaurus** [comment]
I believe this is all done.  Closing.
