### ISSUE TITLE
Cookies are being set without secure flag

### ISSUE THREAD

**Issue by NoahKunin** [18F/midas#702]
This allows things like session tokens to be sent over HTTP. While all sites should already comply with HTTPS Everywhere policies, in case a vuln is found that can circumvent HTTPS this allows for an additional layer of defense.

Reference:
https://www.owasp.org/index.php/Testing_for_cookies_attributes_(OWASP-SM-002)

Seems like Sails is responsible for setting this.

**Comment by dhcole** [comment]
Verified on the dev server:

![screen shot 2015-04-20 at 2 46 30 pm](https://cloud.githubusercontent.com/assets/170641/7237826/20da9d82-e76c-11e4-8340-5b4cf81dd943.png)
