### ISSUE TITLE
Missing third party icon via Oauth login?

### ISSUE THREAD

**Issue by NoahKunin** [18F/midas#703]
Clicked too fast, will grab screenshot later.

**Comment by ultrasaurus** [comment]
@NoahKunin no idea what this means...

**Comment by NoahKunin** [comment]
Here is the screenshot:

![screen shot 2015-04-15 at 4 17 13 pm](https://cloud.githubusercontent.com/assets/565071/7168374/f2e1b364-e38a-11e4-9bce-ec0410e7eb6a.png)

To trigger it, sign up for Midas using a Gmail account that has never logged into Midas before. After clicking the MyUSA option, but before being redirected to Midas, this screen is displayed to confirm the action.

**Comment by dhcole** [comment]
@ultrasaurus is there a place in myusa to upload / link a logo?

**Comment by dhcole** [comment]
@ultrasaurus Looks there is a setting for this in the MyUSA configuration:

![screen shot 2015-04-20 at 2 26 58 pm](https://cloud.githubusercontent.com/assets/170641/7237419/577200e0-e769-11e4-8278-9f562ad66bfc.png)

Here's the URL for the logo: https://midas.18f.us/images/logo-square.png

Can you drop that in? I think only you have access to edit these settings.

**Comment by ultrasaurus** [comment]
There is a logo specified here:
![image](https://cloud.githubusercontent.com/assets/41906/7237529/f4908b9e-e750-11e4-90bc-5cae34aa43ee.png)

**Comment by ultrasaurus** [comment]
@dhcole I will file a MyUSA bug

**Comment by adelevie** [comment]
Huh. Thanks for reporting this. Taking a look now.

**Comment by adelevie** [comment]
@ultrasaurus I'm having trouble reproducing this since my GSA email already has a Midas account. Could you delete my Midas account?

**Comment by ultrasaurus** [comment]
@adelevie please use https://midas-dev.18f.us -- you should be able to auth with any gmail account

**Comment by adelevie** [comment]
Thanks, @ultrasaurus!

**Comment by dhcole** [comment]
Resolved upstream.

**Comment by dhcole** [comment]
Verified with a new email address:

<img width="619" alt="screen shot" src="https://cloud.githubusercontent.com/assets/170641/8532350/9943d358-23fb-11e5-8b07-94cd7bad130a.png">
