### ISSUE TITLE
If you are not logged in and you try to post a comment, you should be prompted to log in.

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#706]
It used to be that it would just not show the topic button:
![image](https://cloud.githubusercontent.com/assets/41906/7115956/4700f5c6-e1a2-11e4-9ec5-233f9eb862f2.png)

That approach would be fine to, but the prompt should really "Sign in to start the discussion" if you are not signed in

**Comment by ultrasaurus** [comment]
@brandtheisey were going to take a look at this?

**Comment by dhcole** [comment]
Looks like this now:

![screen shot 2015-04-17 at 9 52 32 am](https://cloud.githubusercontent.com/assets/170641/7203280/870c0758-e4e7-11e4-9d4a-d9f69761ca58.png)
