### ISSUE TITLE
As a member, I expected to be able to connect my linkedIn account witout clicking "Edit Profile"

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#707]
When I go to my profile, I see:
![image](https://cloud.githubusercontent.com/assets/41906/7117579/6fb54a42-e1ae-11e4-96aa-9b69871cc426.png)

Expected:
![image](https://cloud.githubusercontent.com/assets/41906/7117585/7d030928-e1ae-11e4-9e2e-0ac61bbbde20.png)

**Comment by ultrasaurus** [comment]
Interested in what other people expect... so I've added question tag

**Comment by dhcole** [comment]
Related to #812 and blocked by a major change in the Linkedin API. Closing for now since we have no workaround at the moment.
