### ISSUE TITLE
As a member, when I edit my profile and try to connect LinkedIn (when another account uses that LinkedIn), it does not actually connect the account

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#708]
1) Go tp my profile page
2) click "Edit Profile"
3) Click [+ Connect] next to LinkedIn
4) re-direct to OAuth page, type in name + password
5) re-direct to Profile edit page
still see [+ Connect] next to LinkedIn

If I save the profile, it does not appear to be connected

**Comment by dhcole** [comment]
Started to look into this. Connect works for MyUSA but not LinkedIn. Moving out of the milestone so it's not blocking the release, but I'll assign this to myself to figure out.

**Comment by dhcole** [comment]
@ultrasaurus is it possible you already have another account associated with your Linkedin profile? 

I can recreate what you're reporting when I have one account created by authenticating with Linkedin (which uses my gmail email address), then logging into my @gsa.gov account and trying to connect to my Linkedin account.

If I just connect an existing account to Linkedin with no other account associated with it, the accounts are connected.

The reason this is coming up seems like it's that we don't have our GSA accounts as our primary address for Linkedin, as opposed to MyUSA. When you have the same primary email, the credential would be added and you wouldn't be able to create two accounts with the same email address.

So what do you want to do about this? This is an edge-case but probably a common one. The easiest path would be to disallow signing in (and creating a new account) based on LinkedIn, but still allow for connecting Linkedin to an existing account.

Other than that... seems like we'd need to build some sort of feedback to the user that says "this Linkedin profile is already connected to another Midas account." But to make that a useful warning, we'd need to offer a way to merge accounts... which leads down a bloated path.

Can you think of other approaches that would be preferable?

**Comment by ultrasaurus** [comment]
@dhcole that is exactly the issue.  It's a little weird since my LinkedIn account is disabled.

This won't happen on Open Opportunities since it never had LinkedIn authentication ON and that isn't planned, but we might still consider making it possible to untangle this with:
1) an error that says what is happening
2) make it so admin can delete an account, not just disable it

**Comment by dhcole** [comment]
Cool. Those steps sound like a good approach.

How do you you want prioritize this?

**Comment by dhcole** [comment]
@ultrasaurus I think this is covered by #729. Allowing admins to delete users can be a separate task.
