### ISSUE TITLE
As a volunteer, I should be notified if I am de-selected as a volunteer

### ISSUE THREAD

**Issue by brandtheisey** [18F/midas#709]
The act of an admin or owner deleting a volunteer should generate a notification indicating that the user hadn't been chosen for a the task they had volunteered for.

**Comment by ultrasaurus** [comment]
Proposed text

To: Participant
cc: Opportunity Creator
Subject Line: An update on [Opportunity name here]

Hi [participant’s name],

Thanks again for your interest in [Opportunity name here]. We wanted to let you know that someone else was selected for this Opportunity, but plenty of others are still available! 

To see a selection of currently available Opportunities, please [click here](/tasks). 

Once again, thanks for your interest in this Opportunity. If you have any questions, please don’t hesitate to reach out.

Have a great day,

the SystemName team
