### ISSUE TITLE
disable autocomplete on password fields

### ISSUE THREAD

**Issue by dhcole** [18F/midas#710]

**Comment by dhcole** [comment]
@NoahKunin During your review, you mentioned that we should disable autocomplete on the login password field. As I understand, we can't do this for just passwords -- the setting applies to the whole form. Also, support for this is being removed in FireFox, is not present in IE11. It seems like browsers are moving away from allowing developers to disable autocomplete.

The argument for autocomplete is that it allows password manager applications to take over the password setting process. This can actually be safer for users in that a password could be randomly generated and kept encrypted without ever appearing in plaintext.

Am I understanding your request? If so, with this discussion in mind, what should we do here to meet the standards for getting an ATO?

Sources:

- https://bugzilla.mozilla.org/show_bug.cgi?id=956906
-http://security.stackexchange.com/questions/49326/should-websites-be-allowed-to-disable-autocomplete-on-forms-or-fields

**Comment by ultrasaurus** [comment]
@NoahKunin drawing your attention to this, since we're starting up ATO work again

**Comment by NoahKunin** [comment]
@dhcole I'm convinced! I did not know about the relation to autocomplete from password managers, which I'm totally in favor of and use myself. Resolved!
