### ISSUE TITLE
when deleting an event, the text of the (x) button should not be selectable

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#719]
On Mac Chrome, I get a little I-beam text selection cursor when I roll over the (x) for an event (which I can do as an admin) -- I think this happens for most (all?) browsers and can make it "feel" like the button can't be clicked, but it actually works fine

**Comment by ultrasaurus** [comment]
@brandtheisey: can you take a look at this? should be a quick fix, would be nice to get it into this release

**Comment by brandtheisey** [comment]
Addressed in #720
