### ISSUE TITLE
Make auth error handling consistent and robust

### ISSUE THREAD

**Issue by sefk** [18F/midas#727]
Repro steps:

1. Log in as an admin user 
2. Select user name, "admin" in dropdown
3. Select user name, "logout" in dropdown

Symptom: ugly page with just "forbidden", screenshot below.

Should be: redirect to home page would be fine.

There are other places in the app where logging out doesn't give a great experience, for example when looking at the profile page. In that case you get an error ("not authorized") but at least are immediately prompted to log in with the login modal, so not as bad.

![screen shot 2015-04-21 at 10 17 55 am](https://cloud.githubusercontent.com/assets/621565/7258194/c8ce3352-e80f-11e4-9c5e-37ab25fdf14c.png)

**Comment by ultrasaurus** [comment]
thanks for writing this up!

**Comment by sefk** [comment]
I looked into this a bit and don't think there is a general way to handle, unfortunately. Access enforcement is handled by Sails in ```policies.js```, not in the controller itself as I thought. The fix would be going page by page and putting in redirects, more trouble than its worth. I propose closing this as wontfix. Thoughts?

**Comment by ultrasaurus** [comment]
From reading various web articles, (like [this one](http://iliketomatoes.com/implement-passport-js-authentication-with-sails-js-0-10-2/) see step 8), it appears that we can do a re-direct from the policy itself.  However, our end-points are mostly APIs called from our single-page backbone app.  I wonder if we should do the "re-direct" client-side by navigating to the home page after log out and/or whenever we get a 403 from the server (like with requireUserId policy).

**Comment by sefk** [comment]
That article is a good pointer @ultrasaurus. That points to a good approach, but the "requireUserId" policy is so pervasive, I don't believe the right thing to do is to change that policy everywhere.

Here's what I think we should do: add a new policy, "redirectWithoutUserId", that instead of returning 403, will redirect to the homepage, literally "/". We can use that policy for pages where staying on the current page makes no sense, like profile. We can use this for this initial case, and if there are others, we can switch incrementally. Doing it this way makes it easy to test. I'll code this up now and submit a PR.

**Comment by sefk** [comment]
I was confused by backend / frontend. Indeed the backend already handles this correctly, returning a 403 when you're not logged in, so there's nothing more we want to do with sails or policy. The question is how to have the frontend respond to it. I now don't think that should be handled generally. For profile having it show as an error page and requiring login isn't so bad. The problem is with admin, once you log out there, there's no place for you to go.

Submitted PR #747 for the simpler fix.

**Comment by sefk** [comment]
This bug has morphed into a much bigger thing, generally handling auth errors. Changing bug title to reflect that.

**Comment by dhcole** [comment]
Closed by #747
