### ISSUE TITLE
Enable CSRF protection in backend and frontend

### ISSUE THREAD

**Issue by sefk** [18F/midas#728]
Midas is currently vulnerable to CSRF attacks. [Sails has good support][s] for csrf token issuing and checking, so that's good. That should be easy enough to turn on. On the backbone side it appears that the way is to [muddle with Backbone's sync event][b], maybe the destroy call too? That needs some playing with, of course.

  [s]: http://sailsjs.org/#!/documentation/concepts/Security/CSRF.html
  [b]: http://blog.softr.li/post/43146401263/finally-correctly-dealing-with-rails-csrf

**Comment by dhcole** [comment]
:+1: also need to check for any forms that submit HTTP POST requests. Not sure off hand, but I think there may be some.
