### ISSUE TITLE
As a member, when I add a skill or topic on my profile, it is confusing to see the "none" tag

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#737]
I think we should just hide "None" as soon as someone adds one tag.

![image](https://cloud.githubusercontent.com/assets/41906/7325455/254cbf1c-ea73-11e4-9548-07b82dfaed61.png)

save then see:
![image](https://cloud.githubusercontent.com/assets/41906/7325467/359766ec-ea73-11e4-87d2-8d3f8ab58dc2.png)

When I add a new one, the UI makes more sense, since I can also delete existing tags:
![image](https://cloud.githubusercontent.com/assets/41906/7325483/537b8814-ea73-11e4-9c8d-63977b9952d9.png)

**Comment by awhig** [comment]
I think it might be better, when in edit profile mode, the yellow tags are not displayed at all. The tags are only shown and manipulated in the edit box. Yellow tags are then only shown in read only mode.

This would be less confusing (deleting current tags happens in the same area that you add new tags), but also takes care of the original "none" tag issue.

**Comment by dhcole** [comment]
@awhig, so have all the tags, current and new, in the input field? That makes sense to me. Good idea.

**Comment by awhig** [comment]
I made the change in the PR. All tags, new and old, are now shown in the edit box. The yellow tags are not shown in edit mode.
<img width="409" alt="screen shot 2015-08-11 at 10 17 24 am" src="https://cloud.githubusercontent.com/assets/6233406/9204468/468060fe-4012-11e5-9c9f-f11cb9511699.png">
