### ISSUE TITLE
As a dev, when trying to initialize database - the following error is shown

### ISSUE THREAD

**Issue by kobekoto** [18F/midas#739]
> midas@0.3.1 init /Users/kobeosei-akoto/sites/midas
> mocha test/test.upstart.js --development --recursive test/init

lifting sails: env=development
Loading...  /Users/kobeosei-akoto/sites/midas/config/application.js
Loading...  /Users/kobeosei-akoto/sites/midas/config/assets.js
Loading...  /Users/kobeosei-akoto/sites/midas/config/auth.js
Loading...  /Users/kobeosei-akoto/sites/midas/config/settings/auth.js
Loading...  /Users/kobeosei-akoto/sites/midas/config/bootstrap.js
Loading...  /Users/kobeosei-akoto/sites/midas/config/connections.js
Loading...  /Users/kobeosei-akoto/sites/midas/config/controllers.js
Loading...  /Users/kobeosei-akoto/sites/midas/config/csrf.js
Loading...  /Users/kobeosei-akoto/sites/midas/config/email.js
Loading...  /Users/kobeosei-akoto/sites/midas/config/globals.js
Loading...  /Users/kobeosei-akoto/sites/midas/config/http.js
Loading...  /Users/kobeosei-akoto/sites/midas/config/io.js
Loading...  /Users/kobeosei-akoto/sites/midas/config/log.js
Loading...  /Users/kobeosei-akoto/sites/midas/config/models.js
Loading...  /Users/kobeosei-akoto/sites/midas/config/policies.js
Loading...  /Users/kobeosei-akoto/sites/midas/config/routes.js
Loading...  /Users/kobeosei-akoto/sites/midas/config/session.js
Loading...  /Users/kobeosei-akoto/sites/midas/config/env/development.js
Loading...  /Users/kobeosei-akoto/sites/midas/config/settings/analytics.js
Loading...  /Users/kobeosei-akoto/sites/midas/config/settings/auth.js
Loading...  /Users/kobeosei-akoto/sites/midas/config/settings/emailTemplates.js
Loading...  /Users/kobeosei-akoto/sites/midas/config/settings/notifications.js
Loading...  /Users/kobeosei-akoto/sites/midas/config/settings/sources.js
Loading...  /Users/kobeosei-akoto/sites/midas/config/settings/tags.js
Loading...  /Users/kobeosei-akoto/sites/midas/config/sockets.js
Loading...  /Users/kobeosei-akoto/sites/midas/config/version.js
Loading...  /Users/kobeosei-akoto/sites/midas/config/views.js
Loading...  /Users/kobeosei-akoto/sites/midas/config/env/development.js
  init:
    1) tags

Lowering sails

  0 passing (2s)
  1 failing

  1) init: tags:
     Error: done() invoked with non-Error: Error: Register unsuccessful. {
  "error": null,
  "message": "Your account is disabled."
}
      at /Users/kobeosei-akoto/sites/midas/node_modules/mocha/lib/runnable.js:239:25
      at /Users/kobeosei-akoto/sites/midas/test/init/init/init.test.js:34:23
      at Request._callback (/Users/kobeosei-akoto/sites/midas/test/demo/data/utils.js:39:22)
      at Request.self.callback (/Users/kobeosei-akoto/sites/midas/node_modules/request/request.js:368:22)
      at Request.EventEmitter.emit (events.js:98:17)
      at Request.<anonymous> (/Users/kobeosei-akoto/sites/midas/node_modules/request/request.js:1219:14)
      at Request.EventEmitter.emit (events.js:117:20)
      at IncomingMessage.<anonymous> (/Users/kobeosei-akoto/sites/midas/node_modules/request/request.js:1167:12)
      at IncomingMessage.EventEmitter.emit (events.js:117:20)
      at _stream_readable.js:920:16
      at process._tickDomainCallback (node.js:459:13)

npm ERR! midas@0.3.1 init: `mocha test/test.upstart.js --development --recursive test/init`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the midas@0.3.1 init script.
npm ERR! This is most likely a problem with the midas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mocha test/test.upstart.js --development --recursive test/init
npm ERR! You can get their info via:
npm ERR!     npm owner ls midas
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.0.0
npm ERR! command "/usr/local/Cellar/node/0.10.25/bin/node" "/usr/local/bin/npm" "run" "init"
npm ERR! cwd /Users/kobeosei-akoto/sites/midas
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/kobeosei-akoto/sites/midas/npm-debug.log
npm ERR! not ok code 0

**Comment by dhcole** [comment]
That error means that the user created for running the `init` script has been disabled, and this is done to prevent the `init` script from being run more than once and potentially overwriting data.

Is it possible you've run `npm run init` on the same database more than once?
