### ISSUE TITLE
script the setup

### ISSUE THREAD

**Issue by afeld** [18F/midas#741]
It seems like most of the setup steps are straightforward, and could be easily moved to a bash script. Would be super helpful in making the setup process go faster, as well as reducing potential for user error. General discussion here:

https://github.com/18F/open-source-program/issues/62

@kobekoto I believe you started working on this at [the workshop](hackerhours.org/oss-workshop.html) yesterday? How's it going?

**Comment by afeld** [comment]
@ultrasaurus pointed out that a bash script wouldn't work on Windows, which means maintaining two separate scripts, or a bash script and a set of instructions. What if people had to install Node first (whatever way is appropriate for their platform), then run a Node script to do the rest?

**Comment by ultrasaurus** [comment]
It might be worth refactoring so INSTALL.md links to a separate INSTALL-Mac, INSTALL-Windows, etc. then have a shorter docs with common npm instructions.

Also realized that we kind of skip over how to make an admin user, which might be helpful to folks.

**Comment by dhcole** [comment]
This should be much easier now that the app is available as a Docker container. No command line necessary to get it running. https://github.com/18F/midas/blob/devel/INSTALL.md#deploy-midas-as-a-docker-container-from-the-docker-hub-mac-windows-linux
