### ISSUE TITLE
Should we display names under people's pictures

### ISSUE THREAD

**Issue by brandtheisey** [18F/midas#743]
Something like this:
![screen shot 2015-04-27 at 12 26 37 pm](https://cloud.githubusercontent.com/assets/7915386/7352303/ba0a56fc-ecd8-11e4-8bb2-e0267a78be37.png)

A number of our users expressed confusion over the appearance of these user images particularly if the person has no personalized pic or other information.

**Comment by ultrasaurus** [comment]
I like this idea.  @LisaLNelson -- what do you think?

**Comment by jamesarosen** [comment]
If space is limited (the above image shows the names overflowing the width of the avatars), you could abbreviate: "Tammy C" and "Bobba G." If you do, I recommend letting users override the abbreviation since any algorithm will get some names wrong.

**Comment by ultrasaurus** [comment]
Another idea is to put them on multiple lines if they don't fit and elipses for really, really long names.  I think most first/last will fit.  There are lots of same first names + last initial -- too many Sarah's and Dave's in America :)

**Comment by dhcole** [comment]
Closed by #856
