### ISSUE TITLE
as an admin, if I reload the app on the admin page, I lose the "Adminstration" menu

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#748]
Found locally, reproduced on https://midas-dev.18f.us version 0.3.2 (but not likely a new bug)

Steps:
1) Log in as an Admin
2) Choose "Adminstration" from top-right menu
3) You should be at: https://midas-dev.18f.us/admin/dashboard
4) Refresh the page

Results: "Adminstration" is missing from the menu 

Navigating elsewhere the problem remains, not fixed by a refresh:

![image](https://cloud.githubusercontent.com/assets/41906/7374467/6936f816-ed87-11e4-9a94-e9019d8ca83b.png)

**Comment by sefk** [comment]
I've traced this to a change made by @dhcole on 4/24 -- e5246db.  The offending change is in ```views/layout.ejs``` 

MIdas uses a cached user object in a bunch of places, ```window.cache.currentUser```. This can be populated when you successfully log in, or marshaled up in a response from the backend. That layout template is how we unpack the metadata in the server response foro things like the system name and the  "backendUser".

When set from the result of a successful login, you see this:

    window.cache.currentUser.isAdmin = true

When it comes from the backend, you see this:

    window.cache.currentUser.isAdmin = "true"

Quotes. This gets us into the land of [JavaScript truthiness comparisons][tt]. The interpretation of ```false``` and ```"false"``` changes depending on what operator we're using to compare. The template that renders the Administration menu item happens to compare with ===, so it notices the change, but other places may not.

This could be breaking lots of other things, tough to tell how. I would consider this a 0.3.2 release blocker. Not sure how to safely undo without talking to @dhcole, his change was there for a reason.

  [tt]: https://dorey.github.io/JavaScript-Equality-Table/

**Comment by ultrasaurus** [comment]
@sefk thanks for diagnosing the issue.  0.3.2 hasn't gone live to real users yet.  cc'ing @brandtheisey so he knows

@dhcole should be able to look at it first thing tomorrow

**Comment by dhcole** [comment]
Should be an easy fix. I'll take a look. Thanks for catching it.

**Comment by dhcole** [comment]
Ready in #749

@ultrasaurus how do you want to release this? Should I amend the previous tag to include it, or do a new release? Would that be 0.3.3?
