### ISSUE TITLE
as a user, I would like to see a more helpful search prompt

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#753]
We currently have help text "I'm looking for.."
![image](https://cloud.githubusercontent.com/assets/41906/7396888/89a51ccc-ee59-11e4-8821-689ca7f74e6d.png)

I think @arena's suggestion would be more helpful...
![image](https://cloud.githubusercontent.com/assets/41906/7396868/6839bc6e-ee59-11e4-8d6d-e8e685b9aa52.png)

Fir our current UI,  /tasks would say:
I'm looking for opportunities by name, agency, skill, topic, description...

/projects would say:
I'm looking for working groups by name, agency, skill, topic, description...

**Comment by dhcole** [comment]
Fixed by #857
