### ISSUE TITLE
Don't display a project image if none is uploaded on Browse Projects

### ISSUE THREAD

**Issue by brandtheisey** [18F/midas#759]
Currently if you don't upload an image when creating a project, browse projects looks like this:

![screen shot 2015-04-30 at 2 42 00 pm](https://cloud.githubusercontent.com/assets/7915386/7420022/1dec05d8-ef47-11e4-8d30-49713237e265.png)

The proposal is to not show the default image if a custom image isn't uploaded, which would look like this:
![screen shot 2015-04-30 at 2 59 20 pm](https://cloud.githubusercontent.com/assets/7915386/7420329/8f8a1b42-ef49-11e4-87b0-8aa6fb4da40b.png)
This causes people's projects to pop if they have taken the time to upload an appropriate image.

Alternatively, look how much better the page looks if everyone pics a unique and appropriate image, so we should add uploading an image to the Project creation work-flow/madlibs:

![browse_pprojects](https://cloud.githubusercontent.com/assets/7915386/7419658/81660f94-ef44-11e4-8ba8-2cb7ef09509b.png)

**Comment by ultrasaurus** [comment]
:+1:

**Comment by awhig** [comment]
I think this can be closed. This change is seen in the current builds.

**Comment by dhcole** [comment]
Right, fixed in #858
