### ISSUE TITLE
Allow admins to delete users

### ISSUE THREAD

**Issue by dhcole** [18F/midas#765]
Following up on #708, if a user has an account linked to an oauth account,  and they want to switch that link to another account, an admin may need to delete the original account.

**Comment by ultrasaurus** [comment]
Also might be needed to clean up the duplicate users from https://github.com/18F/midas/issues/548

**Comment by dhcole** [comment]
We've refactored authentication and fixed the issue with duplicate users. We've also locked down sign-up to .gov email addresses and removed existing duplicate users. From this point forward, admins should be able to manage users by disabling them in the admin user dashboard.
