### ISSUE TITLE
saving location tags is no longer saving extra data (lat, long, source, etc.)

### ISSUE THREAD

**Issue by sefk** [18F/midas#768]
When user edits their profile and sets a loctions we need to save the extra data with the location tag -- lat, long, etc. To be stored in ```tagentity.data```.  I've confirmed that it is coming back from the autocomplete endpoint, just not getting carried along and set on the tag when its created.

In this screenshot you can see prior tags with the data column present, and the new ones without.

![missing-tag-data-screenshot](https://cloud.githubusercontent.com/assets/621565/7485334/deb0d8e8-f348-11e4-9f1b-f7fda4c0e8fa.png)

**Comment by dhcole** [comment]
Thanks for catching. I'll get this patched before we roll to production.
