### ISSUE TITLE
As a developer, I don't see demo avatars locally, but see them on midas-dev

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#784]
Did this break recently?

On midas-dev, I see:
![image](https://cloud.githubusercontent.com/assets/41906/7622567/9354eb1c-f985-11e4-91ee-b72c1233121f.png)

locally I see:
![image](https://cloud.githubusercontent.com/assets/41906/7622573/a9c7d814-f985-11e4-85a7-c3b61ee7c316.png)

**Comment by brandtheisey** [comment]
Did you run the local file migration script?

**Comment by ultrasaurus** [comment]
@brandtheisey the local file migration isn't in the branch I was on, but @sefk will try merging, in case it fixes the issue

**Comment by sefk** [comment]
Blocked on #785

**Comment by dhcole** [comment]
@ultrasaurus this should be cleared up. Can you try again and close / post back here with result?
