### ISSUE TITLE
Upgrade dependency on marked, potential dos vuln

### ISSUE THREAD

**Issue by sefk** [18F/midas#793]
Our [Dependency check][gemn] shows a bunch of modules out of date (that's fine) except for one that reports a potential regexp dos vulnerability. This is the dependency check we link to at the top of our README file, so this why we get a very [visible "red" there][proj]

Our package.json expedcts version "^0.3.3". By the [semver][], that means that we'll work work anything 0.3.0 or later. 0.3.3 is vulnerable. 

But what to upgrade to? This [vulnerability][] was reported on 22-Jan of this year an update doesn't seem to be forthcoming. Maybe this package is unsupported now? See this [Github Issue][issue]. So the right fix for this might be selecting another package. A few others in that bug say they are switching to [markdown-it][].

  [vulnerability]: https://nodesecurity.io/advisories/marked_redos
  [proj]: https://github.com/18F/midas
  [gemn]: https://gemnasium.com/18F/midas/alerts#alert-1102579
  [issue]: https://github.com/chjj/marked/issues/497
  [semver]: https://github.com/npm/node-semver
  [markdown-it]: https://github.com/markdown-it/markdown-it

**Comment by ultrasaurus** [comment]
@dhcole can you take a look at this?

**Comment by dhcole** [comment]
Thanks for reporting @sefk. I think the DOS attack is really only relevant for server-side use of marked. We're only using it on the client. 

Worst that would happen if someone entered input like the test case is that the browser tab will spike in CPU usage. I tried this locally and the UI was still responsive (in chrome).

So I don't think we're have any immediate risk with this version. I subscribed to the upstream issue and will upgrade when I new version becomes available.

**Comment by sefk** [comment]
I'm fine with the resolution as closed. Just a bummer that that means that
the project will remain having a red "dependencies: update!" on the top of
our github page. I'm not advocating removing the dependency widget. Arguing
that we should consider upgrading for that reason, and because it may be an
orphan now.
