### ISSUE TITLE
Need to refresh to see uploaded profile image

### ISSUE THREAD

**Issue by nhu313** [18F/midas#800]
When I upload an image, I can't see it until I refresh the page.

Steps to reproduce:
2. Click on your name, then "Profile"
3. Click "Edit Profile" link on the top right corner
4. Click the camera to upload a photo
5. Watch the network requests
6. Choose a photo
7. Note the progress bar display, but the photo is not displayed
8. Note the network request shows the photo is uploaded and retrieved, yet it is not displayed (perhaps something is wrong with the api?)
9. Manually refresh the page (Cmd + R)
10. Note only the small profile image on top of the right corner is changed
11. Manually refresh the page again (Cmd + R)
12. Note the big profile picture is changed

Note: I signed up using my email.

**Comment by brandtheisey** [comment]
Are you seeing this behavior on https://midas-dev.18f.us/ ? 

What browser and OS are you using?

I just tested this with Chrome from a Mac and cannot duplicate the behavior.

**Comment by nhu313** [comment]
Yes, I'm testing it on (https://midas-dev.18f.us/)[https://midas-dev.18f.us/]. I have Firefox 38.0. I tried it on Chrome and it works fine. Maybe this is firefox problem. Wonder if they're caching something.

**Comment by dhcole** [comment]
#helpwanted for more FireFox testing / debugging.

**Comment by awhig** [comment]
I can repro this on Mac OS X, Firefox 40.
