### ISSUE TITLE
Unable to create opportunity after cancel event creation

### ISSUE THREAD

**Issue by nhu313** [18F/midas#803]
When I open the create Event dialog and close it without filling out anything, then I can't add a new opportunity.

Steps to reproduce:
1. Open a working group details (https://midas-dev.18f.us/projects/11)
2. Click "Add Event"
3. Click "Cancel" when the dialog open
4. Click "Add Opportunity"
5. Check the box to agree to the condition
6. Click "Next"
7. Notice it doesn't do anything

**Comment by brandtheisey** [comment]
Do you get any js errors when this happens? Often this is any indication the server has crashed.

**Comment by nhu313** [comment]
No, I didn't get any error. I am able to create an opportunity if I fill out the event. My initial guess is that maybe the dialog share the same id, but I am not so sure.

**Comment by brandtheisey** [comment]
I can recreate this locally and on my production server.

**Comment by ultrasaurus** [comment]
thanks for reporting this @nhu313 !
