### ISSUE TITLE
Does not register second RSVP to an event

### ISSUE THREAD

**Issue by nhu313** [18F/midas#804]
When I try to RSVP two events at the same time, then the app doesn't register the second RSVP.

Steps to reproduce:
1. Open a group that has more than one event (https://midas-dev.18f.us/projects/11)
2. Toggle the "RSVP" so you're not attending any of the events
3. Refresh the page (optional)
4. Click "RSVP" for the first event
5. Click "RSVP" for the second event
6. Note the reservation was not made for the second event. The app is sending a cancel request instead of RSVP for the second event.

**Comment by brandtheisey** [comment]
![file](https://cloud.githubusercontent.com/assets/7915386/7754070/b0985fa0-ffb7-11e4-9ec2-3338c3337a7f.gif)

@nhu313 is this the behavior you are seeing?

**Comment by nhu313** [comment]
Not quite. I recorded the behavior on my phone (android Firefox) and uploaded the video to midas (haha two birds with one stone.  Video upload works :-) )

https://midas-dev.18f.us/api/file/get/30

Whenever I click on the second rsvp I have to tap it twice. It looks like I have to select the event before rsvp. I don't know if that's related or it is Firefox. But look how strange the first rsvp is. At one point it thinks two people are going.

**Comment by brandtheisey** [comment]
Awesome, thanks for following up.
