### ISSUE TITLE
Open Opportunities should have its own hostname / digitalgov.gov domain

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#811]
openopps.digitalgov.gov

related devops issue: https://github.com/18F/DevOps/issues/133

for history see:
https://github.com/18F/midas-open-opportunities/issues/4

**Comment by dhcole** [comment]
This is all set. There is an S3 bucket for `midas.18f.us` that includes a global 301 redirect to `https://openopps.digitalgov.gov`. 

Requests to http[s]://midas.18f.us are routed through CloudFront to handle the SSL certificate. This means that users using Internet Explorer on Windows XP (1 visitor in the last 30 days) may not get the redirect -- instead they would see an SSL warning message.

Also, just for future reference, CloudFront cannot reach S3 website buckets over HTTPS, so you need to force all origin requests over HTTP. This produced some cache errors for about 40 minutes during the cut-over in regions where no HTTP requests occurred. This should be all cleared up now too.
