### ISSUE TITLE
Performance on /tasks is slow

### ISSUE THREAD

**Issue by dhcole** [18F/midas#813]
Just a general capture of thought about performance on the tasks page.

Page loads on https://midas.18f.us/tasks are taking about 4-5 seconds. This is down by about 50% due to the #656 Tag Associations refactor, but still too high.

![screen shot 2015-05-27 at 2 53 56 pm](https://cloud.githubusercontent.com/assets/170641/7844723/5e4a13e2-0480-11e5-9ec2-47423627ad96.png)

The delay on this page is mostly due to the `/api/tasks` endpoint. The manual association between tagEntities and other models was inefficient. 

Here are additional sources of slowness:

- `/api/file/get/*` used to require querying file blobs from the database. In dev, this is moved to disk or S3, but it's not rolled out to production yet. This accounts for 17% of request time: 
![screen shot 2015-05-27 at 2 55 52 pm](https://cloud.githubusercontent.com/assets/170641/7844777/eb8b89d4-0480-11e5-9325-577dd74e86ea.png)
- Sessions are stored in the main postgres DB (That's what all the `head` requests in the previous chart show). We can move sessions to a separate database to help with this. Sails / Express recommend redis, which should be available in AWS through the Elasticache service
- The `/api/task` endpoint is currently returning more data then necessary. We could limit these requests with pagination. There is an infinite scroll implementation of pagination available in the front-end code, however, we need to confirm that this works well with the search and filters on the `/tasks` page
- There is a `like` query on the `/api/task` endpoint that seems to cause the bulk of slowness now. We could track down where this query is coming from and figure out how to optimize it

**Comment by dhcole** [comment]
It looks like a large part of the problem may be our RDS / AWS environment. I'm running the same version of the code and a new dump of the production database locally, and I see much better performance:

```
davidcole@dc:~/dev/midas$ time curl http://localhost:1337/api/task > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  354k  100  354k    0     0   213k      0  0:00:01  0:00:01 --:--:--  213k

real	0m1.668s
user	0m0.004s
sys	0m0.005s
davidcole@dc:~/dev/midas$ time curl https://openopps.digitalgov.gov/api/task > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  254k  100  254k    0     0  47192      0  0:00:05  0:00:05 --:--:-- 64626

real	0m5.539s
user	0m0.030s
sys	0m0.013s
```
Going to look into whether we need to clean up our production DB in some way or possibly increase its instance size.

**Comment by dhcole** [comment]
Yea, it's pretty small:

![screen shot 2015-06-03 at 12 26 27 pm](https://cloud.githubusercontent.com/assets/170641/7965506/f597701c-09eb-11e5-8e25-753b18264815.png)

I suggest we boost the instance size and see how much that makes a difference.

**Comment by dhcole** [comment]
We're currently running an `db.m1.small	` instance, which costs $0.120 / hour. It's also two generations old, so newer generations have more resources at lower cost.

I recommend we upgrade to a `db.t2.small` instance at $0.072. It has comparable resources, with slightly more memory.

Then we can test to see how well it performance. If it's still not desirable, we can either scale up to a `db.t2.medium` or `db.m3.medium`, or we can switch from magnetic storage to SSD.

Since this may cause a few minutes of downtime, I'm going to start testing different instances on the staging database. 

First, I'll update staging to match the production data so we can benchmark effectively and make sure this is really an instance size issue. Currently, with outdated data, we see this on staging:

```
davidcole@dc:~/dev/midas$ time curl https://openopps-staging.18f.us/api/task > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 73957  100 73957    0     0  33203      0  0:00:02  0:00:02 --:--:-- 33209

real	0m2.237s
user	0m0.032s
sys	0m0.012s
```

**Comment by ultrasaurus** [comment]
seems like a good approach :+1:

**Comment by dhcole** [comment]
Success: staging is now slow too:

```
davidcole@dc:~/dev/midas$ time curl https://openopps-staging.18f.us/api/task > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  255k  100  255k    0     0  42777      0  0:00:06  0:00:06 --:--:-- 72001

real	0m6.116s
user	0m0.033s
sys	0m0.018s
```

Will starting testing instance sizes there.

**Comment by dhcole** [comment]
Very modest improvement with `db.t2.small`. Going to jump up to `db.m3.medium`.

```
davidcole@dc:~/dev/midas$ time curl https://openopps-staging.18f.us/api/task > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  255k  100  255k    0     0  53766      0  0:00:04  0:00:04 --:--:-- 56611

real	0m4.866s
user	0m0.034s
sys	0m0.015s
```

**Comment by dhcole** [comment]
No improvement...

```
davidcole@dc:~/dev/midas$ time curl https://openopps-staging.18f.us/api/task > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  255k  100  255k    0     0  50195      0  0:00:05  0:00:05 --:--:-- 67151

real	0m5.211s
user	0m0.034s
sys	0m0.015s
```

Going to try one more, `db.m3.large`, just to see if we're actually DB-bound. Otherwise, it may be that the web server is too small...

**Comment by dhcole** [comment]
Not much better from the large instance...

```
davidcole@dc:~/dev/midas$ time curl https://openopps-staging.18f.us/api/task > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  255k  100  255k    0     0  53427      0  0:00:04  0:00:04 --:--:-- 70964

real	0m4.896s
user	0m0.032s
sys	0m0.015s
```

So let's try magnetic => ssd

**Comment by dhcole** [comment]
No real SSD performance improvement... onto the web server:

```
davidcole@dc:~/dev/midas$ time curl https://openopps-staging.18f.us/api/task > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  255k  100  255k    0     0  54122      0  0:00:04  0:00:04 --:--:-- 72260

real	0m4.834s
user	0m0.033s
sys	0m0.015s
```

**Comment by dhcole** [comment]
Ok, the webserver is the bound:

```
davidcole@dc:~/dev/midas$ time curl https://openopps-staging.18f.us/api/task > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  255k  100  255k    0     0   101k      0  0:00:02  0:00:02 --:--:--  101k

real	0m2.532s
user	0m0.034s
sys	0m0.017s
```

**Comment by dhcole** [comment]
Looks like the final word is we're processor-bound on the web server. Likely the best approach is a bump up in the web server as well as setting up some caching with nginx...

![screen shot 2015-06-03 at 5 37 32 pm](https://cloud.githubusercontent.com/assets/170641/7972027/58a657ba-0a17-11e5-8d06-67fa11a9ee71.png)

**Comment by dhcole** [comment]
Ok, switched our production instances over to `c4.large`, which now return responses in ~30% of the time we saw originally:

```
davidcole@dc:~/dev/midas$ time curl https://openopps.digitalgov.gov/api/task > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  254k  100  254k    0     0   123k      0  0:00:02  0:00:02 --:--:--  123k

real	0m2.070s
user	0m0.032s
sys	0m0.015s
```

Since we know this is a processor-intense endpoint, I'll look into profiling to see if we can find somewhere to optimize. Our other option is caching.

**Comment by dhcole** [comment]
Goal of sub second response achieved in the above PR ^

```
davidcole@dc:~/dev/midas$ time curl http://localhost:1337/api/task > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  253k  100  253k    0     0   376k      0 --:--:-- --:--:-- --:--:--  376k

real	0m0.682s
user	0m0.005s
sys	0m0.005s
```

**Comment by sefk** [comment]
Nice to get that debugged and improved @dhcole. Being cpu bound on the app tier is a killer.

One more thing to consider: add some CloudWatch alerts to warn you of CPU. >60% over 5 min, something like that.
