### ISSUE TITLE
When someone signs up, we should check to make sure they are a fed

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#816]
Automatically disable the account and send a note saying that they should use their official governemtn email address, but they can send mail to ______ if they feel we were in error.

.gov domain names
http://catalog.data.gov/dataset/federal-executive-agencies-domain-list

.mil & other like edus
http://govt-urls.usa.gov/tematres/vocab/index.php

moved from https://github.com/18F/midas-open-opportunities/issues/46

**Comment by ultrasaurus** [comment]
@LisaLNelson will draft an email

**Comment by dhcole** [comment]
@ultrasaurus Our conversation with Gwynne raised some issues about what domains we should allow. Do you have a clear sense for what this should be? 

If we just go with what usa.gov has compiled, we can get both the `.gov` and non-`.gov` domains for Federal agencies through their API. Here is that list together: https://gist.github.com/dhcole/d52fe28a5be39d829114#file-domains-json

Should we enable access for all of these domains? 

My goal is to make this easy to maintain, so if we can go with this whole list, we will be able to rebuild it with one command to pick up new domains. (We could even call the API directly if we wanted to make it completely automatic). If we want to edit this list, we'll be in the business of maintaining our own list and we'll have to reconcile it manually with upstream changes.

**Comment by ultrasaurus** [comment]
@dhcole the challenge is that the govt-urls.usa.gov contains state .gov (and maybe citites?), for example:  http://govt-urls.usa.gov/tematres/vocab/index.php?tema=22

.gov should be restricted to the federal domains list, then I was thinking we would pull in the .edu and .mil domains from govt-urls.usa.gov

to my knowledge there is no single API that has the list of *federal* government domains

**Comment by dhcole** [comment]
I'm only pulling federal domains. Terms 17 and 11928 and federal non-.gov and federal .gov domains. The gist has the code with this as well as the full list of results from these endpoints. Does that work for you?

**Comment by dhcole** [comment]
If so, would appreciate your thoughts on my questions in the original post.

**Comment by dhcole** [comment]
For the denial message, include the following email address and subject:

- digitalgov@gsa.gov
- Open Opportunities Access Request

**Comment by dhcole** [comment]
Closed by #902
