### ISSUE TITLE
task duration passed notification

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#820]
there should be a notification after the task duration has passed

Subject Line: Still working on [task name here]?

To: Participant
CC: Task Creator

Hi [user’s name],

We noticed [task name here] isn’t marked completed and wanted to check in on your progress – how’s it going?

If you’re still working on this [opportunity/task], please email [task creator name] (CC’d on this email) to let them know.

As always, thanks for your participation in [System Name]. 

Best,

The [Sytem Name] Team

**Comment by ultrasaurus** [comment]
depends on https://github.com/18F/midas/issues/290

**Comment by dhcole** [comment]
The challenge with a time-based notification is that we will need some sort of cron task running to check for overdue tasks. We currently only send notifications instantly in response to user actions.
