### ISSUE TITLE
Missing graphic for call-to-action in top-left of Midas open source page

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#826]
![image](https://cloud.githubusercontent.com/assets/41906/7987654/a351f41e-0a93-11e5-92d9-0ea7e4597775.png)
 
There used to be a blue ribbon on the top-left

**Comment by dhcole** [comment]
Looks like view-source:https://pages.18f.gov/midas/ is serving the index.html file from the master branch instead of the 18f-pages branch. Not sure how 18f-pages is configured -- when you set it up, did you have to specify a branch?

**Comment by dhcole** [comment]
Resolved upstream. https://pages.18f.gov/midas/
