### ISSUE TITLE
As a member, when browsing (profiles, tasks, projects) I want the URL to reflect my current search

### ISSUE THREAD

**Issue by sefk** [18F/midas#832]
If a select a city I get a list of people in that city. But I can't share that link, or hit refresh, or bookmark. If the URL reflected my selection then I get all that stuff naturally.

Thought of this based on @ultrasaurus's comments on #830, which should have the same URL behavior.

**Comment by sefk** [comment]
Now that the profile search (people) has been folded into the rest of "browse" alongside of projects (working groups) and tasks (opportunities) this should be generalized to capture search terms for all browse searches. 

It might make sense to hold this off until the search rewrite / cleanup is done, or at least designed.

**Comment by dhcole** [comment]
Let's resolve this as part of #863
