### ISSUE TITLE
I shouldn't see HTML markup in the UI

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#833]
![image](https://cloud.githubusercontent.com/assets/41906/7991285/f8709f14-0aab-11e5-9dea-14e732050500.png)

**Comment by brandtheisey** [comment]
This was fixed https://github.com/18F/midas/pull/802. Did something revert it?

**Comment by dhcole** [comment]
@ultrasaurus what environment? I think it's just not rolled out to production or staging yet.

**Comment by ultrasaurus** [comment]
https://openopps.digitalgov.gov/tasks  v 0.3.4

**Comment by ultrasaurus** [comment]
Thanks @brandtheisey I think this is exactly the thing you fixed
