### ISSUE TITLE
Several references to old non .gov test servers and Mandrill incoming email

### ISSUE THREAD

**Issue by NoahKunin** [18F/midas#834]
In the documentation, there seems to be references to deprecated domains. Everything needs to move over to .gov. Examples are in the top level README and in email received from the app (screenshot below):

![screen shot 2015-06-04 at 3 02 32 pm](https://cloud.githubusercontent.com/assets/565071/7992140/29f1a55a-0acb-11e5-9dd6-85c879a8efc0.png)

Shouldn't be too difficult to re-map everything, jump into the various DevOps channels if ya'll need help

**Comment by dhcole** [comment]
@ultrasaurus I [changed](2561a3e15e2e02f9e49c70573c48ceb154b71638) the URL in the README and added "community" to "test server". That still has `.us` domain until we rebuild / remap it (due by the end of the month).

Can you check out the Mandrill config? I don't think I have access to configure those settings.

**Comment by ultrasaurus** [comment]
@dhcole I don't see anything in Mandrill that refers to 18f.us -- I think the configuration that generates that email header is in here:  https://github.com/18F/cloud-cutter/blob/master/chef/nodes/openopps_aws.json

**Comment by dhcole** [comment]
Good call. How about I change them to staging: `noreply+staging@openopps.digitalgov.gov` and prod: `noreply@openopps.digitalgov.gov`

**Comment by dhcole** [comment]
Actually, I'll just go with `noreply@openopps.digitalgov.gov` since staging and prod use the same configuration file.

**Comment by dhcole** [comment]
Code change is in. Rebuilding staging to verify.

**Comment by dhcole** [comment]
Verified:

![screen shot 2015-06-08 at 12 34 42 pm](https://cloud.githubusercontent.com/assets/170641/8039907/c5b284a2-0dda-11e5-97a7-cb58401cc4af.png)
