### ISSUE TITLE
Allows for users to sign-up without checking for government email

### ISSUE THREAD

**Issue by NoahKunin** [18F/midas#837]
See screenshot:

![screen shot 2015-06-04 at 4 49 25 pm](https://cloud.githubusercontent.com/assets/565071/7994347/ba0d314a-0ada-11e5-9d13-ea285a7a6022.png)

Appears the system will let me add opps, pwd reset, the works, as well.

**Comment by dhcole** [comment]
Yes, this is true. Currently, Lisa Nelson (the OSCIT admin) get's an email notification and follows up with users who don't have a .gov email. In rare cases, there are reasons for letting them in but usually, she disables their account and tells them to sign up with a .gov. This is only happening on production though -- she's not policing the staging site.

Is automating this a blocker for an ATO?

cc @ultrasaurus

**Comment by dhcole** [comment]
Refs #816

**Comment by NoahKunin** [comment]
Seems like a blocker to me in production. Having this be a single human instead of validation will break _very_ easily, as someone could just flood it with dummy requests due to #836. Also, there didn't seem to be any pre-check in getting the ability to post opps - I could do that right away. 

In general, I like to stay out of design and operations concerns, but this is one of those where we probably do have to step in and say no.

**Comment by ultrasaurus** [comment]
@NoahKunin you can post draft opps, but they won't get auto-published

We have checking for a federal domain queued up (as @dhcole mentioned: https://github.com/18F/midas/issues/816); however, I would lunch to understand what the ATO concern is exactly.  We had planned to give Lisa the ability to review and authorize people who sign up.

I'd like to understand the set of issues you are concerned about here so we can be sure to address them in the sign up flow (and for future deployments that may not require someone to be a federal employee).

**Comment by NoahKunin** [comment]
Sounds good!
