### ISSUE TITLE
As a task creator it is confusing to see the "connected accounts" tab on the Profile page.

### ISSUE THREAD

**Issue by LisaLNelson** [18F/midas#841]
Remove Connected accounts.

![image](https://cloud.githubusercontent.com/assets/9039852/8092253/8817313a-0f86-11e5-831a-b533110c4b4e.png)

**Comment by ultrasaurus** [comment]
If you have no connected accounts, maybe that should just be omitted.

I am connected via MyUSA and it looks like this, which is perhaps a different, related issue:
![image](https://cloud.githubusercontent.com/assets/41906/8096891/f95a9882-0f90-11e5-8b53-4dcd053960e0.png)

When I edit my profile, it looks like this:
![image](https://cloud.githubusercontent.com/assets/41906/8096899/07de40c0-0f91-11e5-9315-f57de56630b4.png)

**Comment by dhcole** [comment]
Will be removed as part of #962
