### ISSUE TITLE
After MyUSA signup and modal close, can't access page

### ISSUE THREAD

**Issue by brethauer** [18F/midas#843]
![image](https://cloud.githubusercontent.com/assets/7635133/8114763/e8e853d6-1044-11e5-83db-045462d5c632.png)

**Comment by dhcole** [comment]
Hmm... did the modal close itself or did you click to close it? I haven't seen this before. I'll keep an eye out for it though. Thanks for reporting @brethauer

**Comment by adelevie** [comment]
Let the MyUSA team know if it's anything on our end!

**Comment by dhcole** [comment]
I'm pretty sure this was due to a caching issue, which we've now addressed with a cache-busting query param in #902. Will be deployed with the next release (next week).

Thanks again for post!
