### ISSUE TITLE
When searching opportunities, HTML tags are displayed

### ISSUE THREAD

**Issue by etsai** [18F/midas#851]
The search bar looks like the following with HTML tags displayed in the suggestion text.

![image](https://cloud.githubusercontent.com/assets/1137295/8175744/d2c449ae-13a3-11e5-924f-fc4d569e243f.png)

The HTML tags look strange there and should be removed.

**Comment by ultrasaurus** [comment]
Thanks for reporting this @etsai -- it has been fixed and rolled out to http://midas-dev.18f.us with https://github.com/18F/midas/pull/802.  We still need to update Open Opps!

**Comment by ultrasaurus** [comment]
resolved with 0.4.0 release
