### ISSUE TITLE
Tags listed on task, project, and profile pages should link to searches

### ISSUE THREAD

**Issue by dhcole** [18F/midas#863]
Via Janelle during testing:

> Is there a way to make those topic areas/skills to the left of the task clickable? I would be interested in clicking on the topic to see what other tasks are available under that topic?

To me, this seems like the missing link that will make tags actually useful to the end user.

**Comment by ultrasaurus** [comment]
@dhcole thanks for writing this up!  We've certainly talked about this a lot, but I looked and couldn't find another issue for it.  Note this related issue:  https://github.com/18F/midas-open-opportunities/issues/71 -- there should be a way to bookmark the resulting search result (or link from a newsletter or email).

**Comment by dhcole** [comment]
The real lift for this issue is improving search to handle filtering by tag instead of just free-text search, and triggering search queries by URL parameters.

There are a few other related issues that we can address as part of the search refactor:

- https://github.com/18F/midas/issues/801
- https://github.com/18F/midas/issues/585
- https://github.com/18F/midas/issues/48

@GailSwanson @ultrasaurus this is what we've captured thus far about things we need to improve with search. I suggest we implement these and then see how that works and whether there are additional things to improve.

If you have other thoughts on what should be considered first priority for search, would you mind listing them here? We can use this issue first round search ticket.

**Comment by brandtheisey** [comment]
I think one thing that would make the issue in #801 go away is showing what matched that caused something to return. So if there's a free text in a description then maybe return 50 characters on other side with the matching string highlighted in some way.
I suppose you could achieve the same results via some sort of score on the returned items but that seems like a much bigger lift.

Also, I think search for Javascript should return user profiles that have Javascript as a skill / topic.

**Comment by dhcole** [comment]
This might be helpful if we want to stay in the world of client-based searching / filtering: https://github.com/NYTimes/pourover

**Comment by dhcole** [comment]
Looks like #801 and #48 touch on the same issue, but https://github.com/18F/midas/issues/801#issuecomment-122029544 provides guidance.

**Comment by dhcole** [comment]
@jeremiak https://github.com/18F/midas/issues/832 deals specifically with persistent URLs for searches
