### ISSUE TITLE
Markdown / HTML for comments displays in admin activity feed

### ISSUE THREAD

**Issue by dhcole** [18F/midas#865]
We're escaping but new rendering the HTML / formatted markdown on the admin activity feed. This means some HTML entities get displayed.

![screen shot 2015-06-22 at 9 26 04 am](https://cloud.githubusercontent.com/assets/170641/8282733/c259abc8-18c0-11e5-85a1-b73f6dd9529e.png)

**Comment by brandtheisey** [comment]
This might be an artifact of the way I added markdown support to comments.

**Comment by brendanwhitfield** [comment]
Somehow they're making their way into the database already escaped
