### ISSUE TITLE
Email link should be configurable to server or client emails

### ISSUE THREAD

**Issue by polastre** [18F/midas#87]
When clicking on the email link, there should be a configuration option to select client or server emails.

Client emails is where the application fires a `mailto:` link to the client.

Server emails is where there is a modal with a text box that allows you to enter an email address or select user(s), and then says "Add a personal message".  The server sends the email on behalf of the user without giving away any personal information about the recipient(s).

Many users do not have email clients installed on their machine (eg, Gmail users), or want to just click "Ok send" and not deal with another application popping up.

If the setting is for the client `mailto:` to be used, then the email address of the recipient should not be disclosed for privacy reasons.

Since @mattlesnake made the decision to go with the `mailto:` approach (me not in favor), /cc'ing him on this.  Assigning to @DanKottke for sprint10.

**Comment by dhcole** [comment]
General trend seems to be toward client links. Closing this as we don't have a need for supporting server-side emails at this time.
