### ISSUE TITLE
Create a Wall of Fame

### ISSUE THREAD

**Issue by dhcole** [18F/midas#871]
The current Open Opportunities [wall of fame](http://gsablogs.gsa.gov/dsic/category/wall-of-fame/) should be implemented in Midas.

Also, this should trigger a notification email to the user: https://github.com/18F/midas/issues/819

**Comment by brandtheisey** [comment]
This will need to be togglable as badges have been asked and answered (NO) at State. I'm also willing to just disable it manually for our build as I personally think it's a good idea, just not for our environment.

So either a toggle or an easy way to just comment out a line works for us.

**Comment by GailSwanson** [comment]
I've blocked out the page and working on the detailed data points for each block.
![screen shot 2015-08-24 at 9 21 08 am](https://cloud.githubusercontent.com/assets/12940398/9442589/422ba22c-4a42-11e5-9320-b0770dea0698.png)

**Comment by GailSwanson** [comment]
Achievements block detail
![screen shot 2015-08-24 at 10 25 52 am](https://cloud.githubusercontent.com/assets/12940398/9444140/9a4f9550-4a4a-11e5-8d27-5d3d1b3bc2ca.png)

**Comment by GailSwanson** [comment]
More interface details
![screen shot 2015-08-24 at 11 00 35 am](https://cloud.githubusercontent.com/assets/12940398/9445015/797d52a4-4a4f-11e5-9584-59dc54113802.png)

**Comment by dhcole** [comment]
Looks great! 

How would you define network connections?

**Comment by GailSwanson** [comment]
Can we model the way that LinkedIn calculates connections? A connection can
be a task creator and their task participants and participants working
together on the same task (multiple participant tasks).

**Comment by jeremiak** [comment]
This looks great, and I started working on it. Two quick questions that I have for you @gailswanson:

0. In your design comps there is no notion of date or time, just the assumption that the activity is reverse chronological order. Is this intended or do we want the date/time of each action to be in this view?
0. How do we calculate the concept of "badges"? Perhaps @dhcole has some insight into this as well.

**Comment by dhcole** [comment]
> Can we model the way that LinkedIn calculates connections? A connection can
be a task creator and their task participants and participants working
together on the same task (multiple participant tasks).

LinkedIn connections are pretty complex. First-degree connections are just people you have explicitly approved a connection with. That concept doesn't exist in Open Opps. Second and third degree connections are extensions of those initial connections.

> How do we calculate the concept of "badges"? Perhaps @dhcole has some insight into this as well.

Tracking the badges conversation in a separate issue: https://github.com/18F/midas/issues/979#issuecomment-136507712

> Open Opportunities This Year So Far

Should this be a rolling 12 month count? Otherwise, would things look bleak in January?

**Comment by dhcole** [comment]
@GailSwanson thinking about this comp more, it looks like we will get some redundant content. Badges get awarded when a task closes, so when a task closes, the activity feed will have an item for "Task X closed with participants A, B, C" and then immediately following that there will be several more items for the same event in the format of "A got a badge for participating in X". Do you think that will be a problem we should address at this time?

**Comment by GailSwanson** [comment]
I thought a bit about that. I don't think it will feel so redundant since
one is badge announcements and the other is a single task completion
announcement. I think we should try it and if it turns out not to produce
what we want in the future, we can iterate.

**Comment by GailSwanson** [comment]
I've redlined the interface with specs.
![midas_wofvisualreview](https://cloud.githubusercontent.com/assets/12940398/9821551/907e42ee-5880-11e5-9101-df51fe01fabf.png)
