### ISSUE TITLE
Public slack link is broken

### ISSUE THREAD

**Issue by jeremiak** [18F/midas#873]
Our contribution guidelines state that we have a public slack room available at [http://chat.18f.gov/](http://chat.18f.gov/) but that link returns a 404 error. What is the best slack channel to raise this issue in?

**Comment by ultrasaurus** [comment]
@afeld fixed this yesterday

**Comment by afeld** [comment]
It keeps going down for some unknown reason :confused: Let me know if you notice it not being accessible.

**Comment by jeremiak** [comment]
Ok, thanks @afeld
