### ISSUE TITLE
Map is black on Open Opps

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#879]
![image](https://cloud.githubusercontent.com/assets/41906/8336216/bbb83fee-1a57-11e5-8ae0-5d0123dedfd3.png)

should look like:
![image](https://cloud.githubusercontent.com/assets/41906/8336234/df3ab398-1a57-11e5-8453-69d4f4c99a3f.png)

**Comment by sefk** [comment]
I'm happy to debug but I'd need a pointer to running their instance (or run in their theme). Maybe they just have custom CSS, and I just need to be pointed to it?

**Comment by ultrasaurus** [comment]
customizations are here:  https://github.com/18F/midas-open-opportunities

**Comment by dhcole** [comment]
Should be resolved with the next deploy, fixed here: eb2b85fc10105518d85b5d4f0ed9010d13a61c6e
