### ISSUE TITLE
Create secret user webcal links

### ISSUE THREAD

**Issue by polastre** [18F/midas#88]
Currently, a user must be logged in to access their calendar at `/api/events/ical` because it uses their cookie to verify their identify.

When using `webcal://` links, Outlook/Calendar/GCal don't have the same cookies/credentials set.

The way this is solved in other systems (eg, GCal or TripIt) is to create a random private string that is publicly accessible.  The user would have to share that string with someone for another person to view their calendar.

This would allow the various Calendar apps to keep themselves continually up to date with the server's calendar using the webcal protocol.

**Comment by ultrasaurus** [comment]
icebox for now
