### ISSUE TITLE
Tag selection prompts to recreate existing tags

### ISSUE THREAD

**Issue by brendanwhitfield** [18F/midas#881]
During tag selection, if an existing tag is found, the "Click to create new tag" choice is still present and functional. This is confusing (given the matches shown below), and can even result in duplicate tags in the database.

![existing-tags](https://cloud.githubusercontent.com/assets/6355971/8361057/cbec33b0-1b3e-11e5-8d46-2e1bab3abbef.png)

**Comment by brandtheisey** [comment]
Can you verify that there are not three different types of tags with a value of CSS in your system?

**Comment by brendanwhitfield** [comment]
That's what I thought at first too, here's the table:

![tagentities](https://cloud.githubusercontent.com/assets/6355971/8363096/da7d03ee-1b4a-11e5-9639-0cda5a7dbd96.png)

One solution could be to return `null` from the [`createSearchChoice`](https://github.com/18F/midas/blob/devel/assets/js/backbone/components/tag_factory.js#L71-L82) function, when the tag already exists. According to the docs, this will prevent it from creating the "add new" choice.

**Comment by brendanwhitfield** [comment]
Turns out, the solution was already implemented, but only on the [admin pages](https://github.com/18F/midas/blob/devel/assets/js/backbone/apps/admin/views/admin_tag_view.js#L50-L53). I'll be submitting the fix soon.
