### ISSUE TITLE
Restrict file uploads to task creator & participants

### ISSUE THREAD

**Issue by dhcole** [18F/midas#883]
Currently, any user can upload a file to any task. Seems like we should lock this down to task creators and admins. @ultrasaurus what do you think?

cc @NoahKunin

**Comment by brendanwhitfield** [comment]
Uploads can also be deleted by anyone, and should probably be locked down as well. I have a fix, but it depends on the change to `ownerOrAdmin` in #878.

**Comment by brandtheisey** [comment]
Volunteers probably need to keep the ability upload / delete files.

**Comment by ultrasaurus** [comment]
Agree with @brandtheisey -- let's keep it to Task Creator/Owners, volunteer/participants, and, of course, admins.  

Not sure a volunteer should be able to delete a file uploaded by someone else, but task owner and admin should be able to do that.

**Comment by NoahKunin** [comment]
Hey team - this (when I was notified on the previous attempt to upload mildly malicious malware during testing) is the first I'm realizing this functionality is present at all. Especially given the current controls re on-boarding new users, I would note the following:

1) This would significantly delay full operation of the platform, as we'd have to stand up significant anti-virus and anti-malware infrastructure (which currently does not exist), as attachments are the **prime** vector for attacks.

2) There's no concept of a budget that I've seen for maintaining costs of giant attachments (is there a limit to the upload size in the current code?)

3) This also forces task owners to often update attachments twice - once potentially on their canonical sites, and another on OpenOpps.

Seems like the thing to do is to allow task owners to associate structured URLs with their task, but not attachments.
