### ISSUE TITLE
CSS Pre-processor preference?

### ISSUE THREAD

**Issue by dwl5986** [18F/midas#887]
The CSS of this project isn't very organized and might really benefit from being pre-processed with SASS or LESS. To those working on this project, do you have any experience with either or these or do you have recommendations on which to use? The goal is to make the CSS easier to work with easier to expand on, and a pre-processor seems to be the way to go. Thoughts?

**Comment by dhcole** [comment]
Interesting question. What do you think? Based on your read on the project's set up and goals, would you recommend one over another? 

We're working on general [front-end guidelines](https://github.com/18F/frontend/blob/draft/css_coding_styleguide/css_coding_styleguide.md#preprocessor) at 18F that recommend SCSS and particularly [Bourbon](http://bourbon.io/) / Neat / Refills. 

@jeremiak and I are also trying out [Materialize](http://materializecss.com/) on another project and liking it thus far. It's available in SCSS as well and brings with it all of the interaction design and research that went into [Material Design](https://www.google.com/design/spec/material-design/introduction.html).

**Comment by dwl5986** [comment]
It would appear as though Bourbon is very similar to SASS and would be good for reorganizing the CSS of the project.

**Comment by dwl5986** [comment]
Doing more research into Bourbon, I think if we want to reorganize the CSS, then that is our best bet. It is built on SASS which is very powerful, and it is in your guidelines anyway so it doesn't make sense to stray away from what you are currently looking to use. Does this seem like something you'd want me to move forward on?

**Comment by dhcole** [comment]
@dwl5986 sounds great. Would love for you to sketch out what this would look like if you're interested. It's not something we're about to do internally, but would welcome a PR on it.

**Comment by rogeruiz** [comment]
Is there still interest in getting this set up?

**Comment by ultrasaurus** [comment]
OMG, yes!

**Comment by rogeruiz** [comment]
Awesome! I have a local branch with some modifications, I will attach it to this issue. Can I get assigned to this issue?
