### ISSUE TITLE
As a task participant, I would like a link to the task in the email confirmation...

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#888]
Here's an excerpt from the email:

We just received your request to claim TASK NAME! Thanks for your interest in this opportunity – we’re glad you’d like to help out.

I expected TASK NAME to be a link to the task.

**Comment by awhig** [comment]
I know this isn't tagged with a "help wanted" label, but thought I'd take a stab at it.

Would you like me to do a fix for this?

Rich

**Comment by dhcole** [comment]
@awhig would love you help with this. Thanks for picking it up (and all the other recent PRs)
