### ISSUE TITLE
Security vulnerability with marked dependency

### ISSUE THREAD

**Issue by monfresh** [18F/midas#901]
Since February, a vulnerability has been announced with the `marked` markdown parser:
```
Marked 0.3.3 and earlier is vulnerable to regular expression denial of service (ReDoS) when certain types of input are passed in to be parsed.

Affected versions: Prior or equal to 0.3.3
Solution: As there is no patch available we recommend switching to another markdown parser or if you are able, help out the project by submitting a patch.
Credit: Barış Soner Uşaklı
Sources: https://github.com/chjj/marked/issues/497 
https://nodesecurity.io/advisories/marked_redos 
```

This vulnerability still hasn't been addressed, so I would recommend switching to a more secure markdown parser. In the GitHub comments, someone mentioned https://github.com/markdown-it/markdown-it.

I discovered this by viewing the midas project on Gemnasium: https://gemnasium.com/18F/midas
It's very much encouraged to keep an eye on your depedencies via Gemnasium to make sure they are up to date and to address any security issues.

**Comment by dhcole** [comment]
Thanks @monfresh! We have been aware of this. It's really only an issue for server-side implementation of `marked`. We only use `marked` on the client, so we haven't prioritized migrating away from it.

More in #835 and #793

**Comment by monfresh** [comment]
Thanks for the info. I just closed the alert so that Gemnasium no longer reports it. You'll also notice that your Gemnasium badge in your README is no longer red. This will prevent anyone else (like me) from thinking that there is an open alert that affects the repo.

In order to acknowledge (tells Gemnasium to stop pestering you) and close (tells Gemnasium the issue is resolved or that your project is not affected) alerts, you need to be signed in. This project was not tied to any Gemnasium account, but now it is tied to our 18F account. If you would like to manage it yourself, I can send you an invitation.

**Comment by dhcole** [comment]
Thanks, that's great! I didn't know we could close it. Sure, would love an invitation to manage the account.
