### ISSUE TITLE
Bad escaping in email subject line

### ISSUE THREAD

**Issue by dhcole** [18F/midas#903]
Via a tester:

>  I got an email when I accepted a task, but formatting in the subject line is off (Let your inner &quot;data detective&quot; out ), it doesn’t recognize the quotes “”

This was on https://openopps-staging.18f.us, version 0.5.0.

**Comment by meiqimichelle** [comment]
FYI, confirmed on live interaction:
![screenshot 2015-07-29 08 27 56](https://cloud.githubusercontent.com/assets/4827522/8961735/c9ad9830-35cb-11e5-87e8-fb6de9b75bfe.png)
