### ISSUE TITLE
Sort tags in a way that makes sense for users

### ISSUE THREAD

**Issue by dhcole** [18F/midas#916]
The new task duration tags look great, but they're sorted by database ID:

<img width="133" alt="screen shot 2015-07-20 at 12 38 42 pm" src="https://cloud.githubusercontent.com/assets/170641/8781487/522ea9ec-2edd-11e5-9c6b-d3643069300c.png">
<img width="179" alt="screen shot 2015-07-20 at 12 38 27 pm" src="https://cloud.githubusercontent.com/assets/170641/8781488/522f0496-2edd-11e5-8b09-fe09ac1be4a9.png">

Could we sort by their logical sequence? One possible solution is to manually sort them in the migration script and set their `createdAt` timestamp to (pseudo) ` now + i`, then alter the front end code to sort them by `createdAt`.

**Comment by jeremiak** [comment]
Cool, that makes sense. In order for the client and API to not be too tightly coupled I think that the API should return all the data required by the client to perform the proper sort.

@dhcole how do I configure Sails to return the entire tag models instead of just the fields defined in `/api/models/TagEntity.js`?

**Comment by dhcole** [comment]
From Slack:

> https://github.com/18F/midas/blob/devel/api/services/sources/model.js#L54-L60
> 
> The request flow goes:  HTTP req /api/ac/tag => ACController => /service/sources/model.js => ACController => HTTP res
> 
> So that service is filtering the model objects to the result object. You probably want to just add in createdAt and updatedAt into those responses. I think the ACController and this whole service could be refactored out.

**Comment by dhcole** [comment]
Using the Blueprint route: `http://localhost:1337/api/tagentity?type=task-length&sort=createdAt%20ASC`
