### ISSUE TITLE
where are the Google analytics?

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#918]
the report I used to look at has zero data since June 3
https://www.google.com/analytics/web/?hl=en#report/visitors-overview/a48605964w90718604p94366104/%3F_u.date00%3D20150101%26_u.date01%3D20150720/

Is there a new place or do we need to fix the code?

**Comment by dhcole** [comment]
I think since we have DAP on Midas now, the analytics only show up in DAP. I'm not sure Midas is properly configured to report to two Google Analytics profiles. Do you have access to DAP?

**Comment by ultrasaurus** [comment]
I understood that DAP == Google Analytics.  analytics.usa.gov doesn't make the data visible for individual websites.  We're supposed to access it through GA

**Comment by ultrasaurus** [comment]
@gbinal can you explain how we can access data for Open Opps -- or point us to the right person?

**Comment by dhcole** [comment]
@ultrasaurus right, DAP is in Google Analytics, but it's a separate profile. You have to request access to the DAP profile in Google Analytics. I'll DM you the form to do so. Closing as this is now an internal access issue.
