### ISSUE TITLE
add 18F Google Analytics Account 

### ISSUE THREAD

**Issue by gbinal** [18F/midas#922]
Per the [18F Analytics Standards](https://github.com/18F/analytics-standards), can we please integrate https://openopps.digitalgov.gov/ into the 18F Google Analytics (GA) account?  

To do so, you'd need to insert [this template](https://github.com/18F/analytics-standards#javascript-code-snippet) and use this UA code - `UA-48605964-17`.

**Comment by gbinal** [comment]
And to https://pages.18f.gov/midas/ as well.

**Comment by jeremiak** [comment]
It appears that the Open Opportunity app already is configured for both DAP and 18F analytics - [see config here](https://github.com/18F/midas-open-opportunities/blob/master/config/settings/analytics.js#L4-L6).

However, looking at the 18F analytics dashboard makes me think that it isn't configured correctly

**Comment by jeremiak** [comment]
Further update. @gbinal we have the following currently being served on Open Opportunities but the 18F GA account doesn't seem to reflect any new data since June 3 (related issue: #918). Any ideas or obviously wrong things with the snippet below?

```
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

     ga('create', 'UA-48605964-17', 'auto');
     ga('send', 'pageview');
   </script>
```

**Comment by dhcole** [comment]
@jeremiak, I think you've made some progress on this over slack, right? Anything we should update here?

**Comment by jeremiak** [comment]
@dhcole the update from Slack is that I'm to implement the new 18F provided snippet. I'll get that PR updated by COB today, should be really straight forward

**Comment by jeremiak** [comment]
Made some changes recommended by @gbinal in Slack in #946 that amount to:

0. Force to use `https://` for the collect call back to GA
0. `anonymizeIp` and `forceSSL` are enabled
