### ISSUE TITLE
Long links break the page layout for tasks

### ISSUE THREAD

**Issue by dhcole** [18F/midas#944]
Issue here: https://github.com/18F/midas-open-opportunities/issues/70

**Comment by awhig** [comment]
I added overflow:hidden to the div.

The link is now clipped. User probably should then add link text, so the display is better.

<img width="629" alt="screen shot 2015-08-11 at 6 26 41 pm" src="https://cloud.githubusercontent.com/assets/6233406/9214840/a08595c0-4057-11e5-9c76-f53fc6799164.png">

**Comment by jeremiak** [comment]
Instead of `overflow: hidden;` we will use `word-break: break-all;`. Thanks again @awhig!
