### ISSUE TITLE
Opportunity Creation Interface Fixes

### ISSUE THREAD

**Issue by GailSwanson** [18F/midas#957]
- [x] Create an Opportunity should be in title case (capitalize “Opportunity”)
- [x] “If you’re new…” copy should be set apart by a padded colored border(not red).
- [x] Link “10 Tips for Creating the Perfect Open Opportunity Task” to http://www.digitalgov.gov/resources/open-opportunities-task-creator-toolkit/10-tips-for-creating-the-perfect-open-opportunity-task/
- [ ] Adjust line spacing to match design 
- [x] Change “All fields required.” to “Optional fields are indicated.” 
- [x] Additional line spacing above step 1 heading.
- [x] Use title case for step headings. (i.e. Create a Headline, Describe the Opportunity)
- [x] Left justify field labels with other text.
- [x] Reduce line spacing within instructional text (above field)
- [x] Italicize instructional text with parentheses (reference wireframe)
- [x] Remove hint text inside headline and description 
- [x] Description instructional text should read: “Write a description that explains the opportunity. Add details so that people can imagine what this will be like when completed. There is no limit on length, but we recommend 200 words or less.)”
- [x] Add line spacing above Tags heading
- [x] Add period at end of Tags instruction text.
- [x] Update in-field hint text to read “Start typing to select a tag.”
- [x] Add rest of One time label: “One time — A one time task with a defined timeline”
- [x] Add rest of Ongoing label: “Ongoing  — Requires a portion of participant’s time until a goal is reached"
- [x] Update “Specific location(s):” to “At specific locations:”
- [x] Add line space above buttons
- [x] Add spacing between buttons so to minimize mis-clicks. Right align buttons on page
- [x] Change “Create” button label to read “Submit for Review”
- [x] Update background on text rectangles to dark grey (#797979) and text as white
- [x] Estimated completion date should be optional
- [x] When Ongoing is selected, display the Example text rectangle at right
- [x] Values for “How often is this time needed?” selector should be: Weekly, Biweekly, Monthly
![screen shot 2015-08-14 at 3 12 41 pm](https://cloud.githubusercontent.com/assets/12940398/9283135/f8a22c3c-4296-11e5-9bc4-89f7b0b02d8f.png)

**Comment by jeremiak** [comment]
Sorry for changing your direct comment, @GailSwanson but I just changed it to be a checklist so I can make sure to address all the issues. For future reference (and you can take a look at the raw text of the comment by editing it above) you can use ` - [ ]` for a checkbox and `- [X]` for a checked checkbox

**Comment by GailSwanson** [comment]
Thanks for the tip!

Sent from my iPhone

On Aug 14, 2015, at 3:19 PM, Jeremia Kimelman <notifications@github.com>
wrote:

Sorry for changing your direct comment, @GailSwanson
<https://github.com/GailSwanson> but I just changed it to be a checklist so
I can make sure to address all the issues. For future reference (and you
can take a look at the raw text of the comment by editing it above) you can
use - [ ] for a checkbox and - [X] for a checked checkbox

—
Reply to this email directly or view it on GitHub
<https://github.com/18F/midas/issues/957#issuecomment-131229597>.

**Comment by jeremiak** [comment]
@GailSwanson should links within the right hand grey boxes also be white? With the background-color set to #797979 the contrast is super low with the link blue.

Screenshot: http://up.jeremiak.com/cEiu

**Comment by jeremiak** [comment]
@GailSwanson another question for you. You have of the items to be corrected as:

> "When Ongoing is selected, display the Example text rectangle at right"

But I don't see any example text rectangle in the design comp specifically to be displayed alongside the ongoing radio button. Is there a design comp I can work off of?

**Comment by jeremiak** [comment]
What does the item "Adjust line spacing to match design" mean? If you could point out the differences off of the current state of the `bug/task-creation` branch and the design that would be helpful.

**Comment by GailSwanson** [comment]
Here is the detail on the form interaction
![18f_midas_taskv2 2](https://cloud.githubusercontent.com/assets/12940398/9306719/bb6826d4-44bf-11e5-870c-721da9b5643d.png)

**Comment by GailSwanson** [comment]
Line height would have been the better term to use. That help?
