### ISSUE TITLE
Profile Page: Look at overall design / usability

### ISSUE THREAD

**Issue by dhcole** [18F/midas#962]
- https://github.com/18F/midas/issues/698
- https://github.com/18F/midas/issues/841

**Comment by GailSwanson** [comment]
Updated layout and badges added
![profile_view](https://cloud.githubusercontent.com/assets/12940398/9937228/72a345ea-5d25-11e5-8131-4e98473af3f2.png)

**Comment by ultrasaurus** [comment]
I think it would be nice to have active projects at the top and history (completed/closed) in another section.  Also, I think we don't have a "Closed" state any more -- it is either completed or archived.

**Comment by GailSwanson** [comment]
Can you share your thoughts on why you would put active projects in a more prominent view/section? As I was looking at the layout, I was thinking about the reasons why someone would look at a profile. Showing the sum of their activity, much like job history, is supportive of the goal to provide a view of someone's skills and experience for their manager. 

Thoughts?

**Comment by ultrasaurus** [comment]
A few different needs:
* People look at their own profile for quick links to their active projects.  
* when I look at someone else's profile, I'm interested in what people are working on right now.  
* from user research: many folks pick projects based on who is posting the project, so they would want to see the open projects by that person

**Comment by GailSwanson** [comment]
In the design, the sort order of opportunities puts open ones at the top of the created and participated lists. If we highlight them a bit more, will that meet the concern? A less fragmented interface provides an easier way to grok the whole list while still providing the ability to easily see what is currently open.

**Comment by GailSwanson** [comment]
Updated design for Edit Profile. The button and input fields are more in-sync with the web standards.
![edit profile](https://cloud.githubusercontent.com/assets/12940398/9977315/c7d70652-5ec7-11e5-83a5-4d87964696c7.png)

**Comment by jeremiak** [comment]
@GailSwanson Something to consider on the profile page (though not in edit mode) is that when the tags get really long it can start lo look sort of weird:
![screen shot 2015-09-21 at 5 13 09 pm](https://cloud.githubusercontent.com/assets/780941/10005267/45b947a2-6084-11e5-9e0e-25b608219740.png)

**Comment by GailSwanson** [comment]
What is the max, min and average number of tags people have in their profiles currently?

**Comment by jeremiak** [comment]
@GailSwanson Good questions. Not quite sure what the max or average number are, I'll try and find out by looking at the staging DB snapshot I have. The minimum number will be 0 though, since they're not required on sign up.

**Comment by GailSwanson** [comment]
Added info block text for edit page.
![profileedit_20150924](https://cloud.githubusercontent.com/assets/12940398/10076020/b4d63d54-629e-11e5-81e5-e56cfc171635.png)
