### ISSUE TITLE
Saving Profile does not work.

### ISSUE THREAD

**Issue by awhig** [18F/midas#971]
I got latest code, and now when saving a profile, it always says Save Failed.

Inspecting the call, I see in the call stack a response with an responseText:

"{ "error": "E_VALIDATION", "status": 400, "summary": "1 attribute is invalid", "model": "Passport", "invalidAttributes": { "user": [ { "rule": "required", "message": "\"required\" validation rule failed for input: null" } ] } }"

Steps to repeat.

1) Create a new user via UI.
2) Login as user
3) Go to profile page
4) Click Edit Profile
5) Click Save Profile button

**Comment by dhcole** [comment]
Thanks @awhig, I'll take a look. Seems like this started in a > 0.7.2 release.
