### ISSUE TITLE
Improve naming and visual representation of badges

### ISSUE THREAD

**Issue by GailSwanson** [18F/midas#979]
As a participant, I would like to see badges displayed with the new names and graphics across the platform. 

*badges*
"Agency Rep" keep name, new graphic
"Founder"  keep name, new graphic
"Tapathon"  keep name, new graphic
"Tapas" gets relabeled "Connection" with new graphic (puzzle piece image)
"20%" gets relabeled "Journey" with new graphic (bicycle)

**Comment by GailSwanson** [comment]
All formerly awarded badges should be converted. 

In a future iteration, we plan to redo the manner in which we award badges so that they are graduated rather than awarding duplicates to an individual. When that is implemented, people will retain their historical badges on their profiles even if those badges are deprecated.

**Comment by jeremiak** [comment]
What are the definitions of those badges? That is to say, how does a user get awarded these various badges?

Is this documented somewhere from the old platform?

**Comment by GailSwanson** [comment]
I don't know if they were documented anywhere, however, the definitions are not complex.

Completing a one time task gets you a Connection badge
Completing an ongoing task gets you a Journey badge
Participants in the Tapathon got a Tapathon badge
There is only one Agency Rep recipient. We will redefine if we decide to award any future ones.
Founder badges will only be those who have already been awarded those badges.

**Comment by dhcole** [comment]
Migrating old badges that we don't plan to support poses a few issues:

1. How do we know who gets those badges? We'd have to manually assign them. What if those users don't have accounts on the new system yet?
2. This would break our current approach, which is that badges would be dynamically generated based on querying data in the database. If these are not going to apply to users who qualify for these conditions in the future, how to we make the distinction?

Have you thought about how we should address these? Can we put historic badges aside for another iteration and focus on new ones since only new badges would apply to the wall of fame feed?

**Comment by GailSwanson** [comment]
Is it not possible to rename/label the old badges that have historically been awarded and continue to award with the new names according to the established algorithm? I'm not recommending changing the algorithm at this point in time, just the names and graphics

**Comment by GailSwanson** [comment]
The tapathon and founders badges won't have additional/future users who meeting those qualifications, so we should be fine on those. The agency rep badge will most likely be in the same boat. 

If/when we decide to change the badging algorithm, we will have to figure out how to maintain the historical badges. That's the big reason I didn't want to up end that part of things with this iteration.

**Comment by dhcole** [comment]
Yea, that's totally fine. I was thinking about the agency rep and founders. For these, we probably need to think about something like a tag instead a query, since they are not awarded based on activity. Can we follow up on those and focus on the activity-driven ones first?

**Comment by GailSwanson** [comment]
After discussion, we will use this opportunity to redefine the badges entirely. The new badges are as follows:

**Name:** Newcomer
**Criteria/Event:** First task completed by user

**Name:** Maker
**Criteria/Event:** 3rd task completed by user

**Name:** Game Changer
**Criteria/Event:** 5th task completed by user

**Name:** Disruptor
**Criteria/Event:** 10th task completed by user

**Name:** Partner
**Criteria/Event:** 15th task completed by user

**Name:** Local
**Criteria/Event:** Completed 2 tasks for one agency

**Name:** Explorer
**Criteria/Event:** Completed Tasks for 2nd agency

**Name:**Connector
**Criteria/Event:** Completed Tasks for 3rd agency

**Name:** Mentor
**Criteria/Event:** Created first ongoing task

**Name:** Team Builder
**Criteria/Event:** Accepted 4 or more people on a task

**Name:** Instigator
**Criteria/Event:** Create first one-time task

**Comment by jeremiak** [comment]
Blocked on this currently as we wait for badge design and artwork.

**Comment by jeremiak** [comment]
Badges can be found here: https://18f.slack.com/files/jj/F0CU83JUF/badges.zip
