### ISSUE TITLE
Need a link to a help section

### ISSUE THREAD

**Issue by Chessen** [18F/midas#98]
We need a link to a help page for users. I'd suggest we use the standard question mark icon in the header. @sharonlo over to you for design.

**Comment by dhcole** [comment]
@ultrasaurus @GailSwanson we have a link to the task creator instructions on the new task creation form. Is there anything else actionable here?

**Comment by GailSwanson** [comment]
The current site doesn't provide any information or paths for anyone with a question or needing help. That's a global issue that can be fixed by enhancing the footer. Worth considering.
