### ISSUE TITLE
installation trouble on ubuntu

### ISSUE THREAD

**Issue by ultrasaurus** [18F/midas#980]
First things first, my current environment:
I’m working on a dedicated physical box,
```
Fresh install of Ubuntu Server 12.04.5
2 X 250Gb HDD into a physical RAID0 array
2Gb RAM
2 dual core Xenon 2.4Ghz processors
```
Following the instructions at https://github.com/18F/midas/blob/devel/INSTALL.md

Everything goes smoothly until I get to the "Install midas node packages (from the midas git folder)” step, I got a ETIMEDOUT error. After some digging I found, for some reason that the proxy flag in the npm config had been set? So I deleted it and re-ran with success.

At the "Setup the database” section, after running "npm run migrate” it generated the attached error. A little more digging I found the pg_hba.conf file entry "# Database administrative login by Unix domain socket” needed to be changed from:
```
-local   all             postgres                                peer
+local   all             postgres                                md5
```
Restarted the postgresql server and ran "npm run migrate” again, this time with success!

Same "Setup the database” section, running "npm run init” I get the attached error. Edited the "# IPv4 local connections:” line in the pg_hba.conf file, re-inserting the line:
host    all             all             127.0.0.1/32            md5
Restarted the postgresql server and no more error!

Where I am currently:
Running the "npm run init” command now, it appears as though everything is processing as it should, but it gets to the line
```
2015-08-26T21:43:39.882Z - debug: --------------------------------------------------------
2015-08-26T21:43:39.883Z - debug: :: Wed Aug 26 2015 21:43:39 GMT+0000 (UTC)
2015-08-26T21:43:39.883Z - debug: Environment : development
2015-08-26T21:43:39.883Z - debug: Port        : 1337
2015-08-26T21:43:39.884Z - debug: ————————————————————————————
```
And just hangs there.

**Comment by ultrasaurus** [comment]
posted this issue that came through email, in case anyone else has ideas.  The only thing I can think of is that the box isn't listening on port 1337.

**Comment by jeremiak** [comment]
> ```
2015-08-26T21:43:39.882Z - debug: --------------------------------------------------------
2015-08-26T21:43:39.883Z - debug: :: Wed Aug 26 2015 21:43:39 GMT+0000 (UTC)
2015-08-26T21:43:39.883Z - debug: Environment : development
2015-08-26T21:43:39.883Z - debug: Port        : 1337
2015-08-26T21:43:39.884Z - debug: ————————————————————————————
```

@ultrasaurus Not quite sure what is meant by "just hangs there" since that bit is sails output that means the server is up and running

**Comment by commradesox** [comment]
Thanks for posting this @ultrasaurus.
@jeremiak When I say it "just hangs there" I mean the cursor sits at the bottom of the page blinking but does not return to a command prompt. So the only way I can resume with the rest of the install instructions is to Ctl+C, stopping the "npm run init" command.
If I do this and carry on with the instructions I get the following error:

    npm ERR! midas@0.7.3-rc.1 demo: `mocha test/test.upstart.js --development --recursive test/demo`
    npm ERR! Exit status 3
    npm ERR! 
    npm ERR! Failed at the midas@0.7.3-rc.1 demo script.
    npm ERR! This is most likely a problem with the midas package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     mocha test/test.upstart.js --development --recursive test/demo
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls midas
    npm ERR! There is likely additional logging output above.
    npm ERR! System Linux 3.13.0-32-generic
    npm ERR! command "/usr/bin/node" "/usr/bin/npm" "run" "demo"
    npm ERR! cwd /midas
    npm ERR! node -v v0.10.37
    npm ERR! npm -v 1.4.28
    npm ERR! code ELIFECYCLE
    npm ERR! 
    npm ERR! Additional logging details can be found in:
    npm ERR!     /midas/npm-debug.log
    npm ERR! not ok code 0

And this is my npm-debug.log:

    0 info it worked if it ends with ok
    1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'demo' ]
    2 info using npm@1.4.28
    3 info using node@v0.10.37
    4 verbose node symlink /usr/bin/node
    5 verbose run-script [ 'predemo', 'demo', 'postdemo' ]
    6 info predemo midas@0.7.3-rc.1
    7 info demo midas@0.7.3-rc.1
    8 verbose unsafe-perm in lifecycle true
    9 info midas@0.7.3-rc.1 Failed to exec demo script
    10 error midas@0.7.3-rc.1 demo: `mocha test/test.upstart.js --development --recursive test/demo`
    10 error Exit status 3
    11 error Failed at the midas@0.7.3-rc.1 demo script.
    11 error This is most likely a problem with the midas package,
    11 error not with npm itself.
    11 error Tell the author that this fails on your system:
    11 error     mocha test/test.upstart.js --development --recursive test/demo
    11 error You can get their info via:
    11 error     npm owner ls midas
    11 error There is likely additional logging output above.
    12 error System Linux 3.13.0-32-generic
    13 error command "/usr/bin/node" "/usr/bin/npm" "run" "demo"
    14 error cwd /midas
    15 error node -v v0.10.37
    16 error npm -v 1.4.28
    17 error code ELIFECYCLE
    18 verbose exit [ 1, true ]

And @ultrasaurus, hopefully you're still reading :-)
output from wget http://localhost:1337 is:

    root@elab:/midas# wget http://localhost:1337
    --2015-09-01 16:22:47--  http://localhost:1337/
    Resolving localhost (localhost)... 127.0.0.1
    Connecting to localhost (localhost)|127.0.0.1|:1337... connected.
    HTTP request sent, awaiting response... 200 OK
    Length: 177 [text/html]
    Saving to: `index.html'

    100%[=================================================>] 177         --.-K/s   in 0s      
    
    2015-09-01 16:22:47 (25.7 MB/s) - `index.html' saved [177/177]

Thanks in advance for any and all suggestions and advice. If you need any more info please don't hesitate to request and I'll try and post as soon as possible.

**Comment by jeremiak** [comment]
Hey @commradesox - thanks for hanging in there and getting through the install process. If you find anything that's wrong (or not specific enough for Ubuntu users) please feel free to document in a pull request for the `INSTALL.md` file.

As far as your current issue, once you run `npm run init` and it gets to that message, the web server should be up and running! Try going to [http://localhost:1337](http://localhost:1337) to access it. Once you're there, you should see the Midas application.

Since you've already run `npm run init` on this database, you can just run `npm run watch` to get started developing on the platform. `npm run watch` will start the server in a way that the build process and server restarting is automatically triggered on each file change (really helpful for when you're developing the application). If you just want to start the application (for instance deploying to a server) then I think `npm start` should be sufficient.

Can you try that and let me know how it goes?

**Comment by commradesox** [comment]
Thanks @jeremiak, the server is up & running now! You can see it at http://elab.parsons.edu:1337/
I guess it just wasn't intuitive to me that I needed to be logged in and keep an open session on the server in order for the it to run and be accessible remotely?

**Comment by ultrasaurus** [comment]
@commradesox you can definitely run the process in the background.  We don't stay logged into our servers!
