### ISSUE TITLE
As an admin I should be able to delete draft tasks.

### ISSUE THREAD

**Issue by LisaLNelson** [18F/midas#987]
We have had multiple people create copies of tasks by accident.  These tasks cannot be deleted by the person or the admin and appear on their profile (e.g. Donald Mills https://openopps.digitalgov.gov/profile/420)

![image](https://cloud.githubusercontent.com/assets/9039852/9823708/04e33eb8-5896-11e5-8309-db99b13f698c.png)

As admin I need to be able to remove those tasks.

**Comment by ultrasaurus** [comment]
We might not be able to get to this for a few weeks, but I'd like to queue it up in case someone can fit it in between things or if we have an open source contributor willing to help.

I think this could be a simple (X) like we do for comments:
![image](https://cloud.githubusercontent.com/assets/41906/9825348/4e169b74-5905-11e5-9fdf-4115e70ba21e.png)


@GailSwanson @jeremiak : any thoughts?
